from commun import DEJEUNER, MOYENS_BASE, PAUSE_APREM, PAUSE_MATIN, VERSION, suivi_standard

F = {
    'ref': 'FOR-0011', 'fichier': 'programme-detaille-for-0011-ia-generative-au-travail.pdf', 'nom_affiche': 'Programme detaille - FOR-0011 - IA generative au travail.pdf',
    'titre': 'IA générative au travail : Gagner du temps chaque jour, en sécurité et avec des preuves (3 jours)',
    'nom': 'IA générative au travail',
    'promesse_titre': 'Gagner du temps chaque jour, en sécurité et avec des preuves',
    'promesse': "En trois jours, chaque participant apprend à bien demander, à protéger les données, à vérifier ce que l'IA produit, à traiter des processus entiers et à construire l'assistant de son poste. L'entreprise repart avec un dossier de preuve des mesures IA prêt à classer.",
    'format_court': 'Présentiel - 3 jours', 'jours': 3, 'heures': 24, 'validation_courte': 'Assistant + dossier de preuve',
    'inter': '790', 'intra': '2 400', 'version': VERSION,
    'public_court': 'tout salarié, manager, dirigeant ou indépendant qui utilise ou va utiliser l\'IA générative.',
    'public': 'Tout salarié, manager, dirigeant ou indépendant qui utilise — ou va utiliser — un outil d\'IA générative : accueil, administratif, commerce, RH, comptabilité, communication, encadrement, direction de TPE-PME. La journée 3 vise aussi la personne qui répond en interne à « est-ce qu\'on a le droit ? ».',
    'prerequis': 'Jours 1 et 2 : savoir utiliser un navigateur et une messagerie. Un compte PROFESSIONNEL sur l\'outil retenu par l\'employeur, jamais un compte personnel. Jour 3 : licence nominative (Copilot, Gemini, Le Chat Pro ou Dust) ou environnement de démonstration fourni.',
    'materiel': 'Poste connecté + compte professionnel sur l\'outil d\'IA de l\'employeur. Jour 3 : licence nominative ou environnement de démonstration fourni.',
    'production': 'Bibliothèque de 10 demandes métier documentées, trois parcours métier menés à terme, un assistant personnalisé, une note d\'arbitrage américain / européen, deux mentions de transparence, trois mesures de gouvernance et la fiche de poste « usages IA ».',
    'outils': 'Voie américaine : Copilot, Gemini, ChatGPT, Claude. Voie européenne : Mistral Le Chat, Dust, modèle local avec Ollama. Enseignées à parité à partir du jour 2.',
    'financements': 'OPCO, plan de développement des compétences, France Travail (AIF), Région Réunion',
    'positionnement': {
        'idee': "On ne forme pas à un outil mais à une manière de travailler : bien demander, ne jamais livrer ce qui ne doit pas sortir, vérifier avant de diffuser, et pouvoir le prouver. Les deux voies, américaine et européenne, sont enseignées à parité.",
        'intro': 'Trois blocs, un par journée :',
        'points': [
            'Bloc 1 — Comprendre et bien demander : ce qu\'est un modèle de langage, la méthode des 4 C, le tri des données, la vérification.',
            'Bloc 2 — Produire dans l\'entreprise : droits d\'accès, deux voies, parcours métier complets, bibliothèque de demandes.',
            'Bloc 3 — Automatiser et prouver : assistant personnalisé, audit de tableaux, gouvernance et dossier de preuve.',
        ],
        'vigilance': "Cette formation n'est ni un diplôme, ni une certification enregistrée, ni une « mise en conformité » automatique : elle aide l'entreprise à prouver les mesures prises pour favoriser la maîtrise de l'IA de ses équipes (IA Act, art. 4).",
    },
    'vocabulaire': [
        ['Modèle de langage', 'Une machine à probabilités qui prédit la suite d\'un texte ; ce n\'est pas une base de connaissances.'],
        ['Méthode des 4 C', 'Casquette, Contexte, Cadre, Contrôle : la structure d\'une demande qui fonctionne.'],
        ['Hallucination', 'Une réponse plausible mais inventée.'],
        ['Anonymiser', 'Retirer ou remplacer ce qui permet de reconnaître une personne avant de saisir un texte.'],
        ['Sur-partage', 'Des droits d\'accès trop larges qui rendent un document visible par l\'assistant.'],
        ['Assistant personnalisé', 'Un assistant configuré pour une tâche récurrente du poste (agent Copilot, Gem, agent Mistral…).'],
        ['Dossier de preuve', 'Les pièces qui montrent les mesures prises : programme, émargements, fiches de poste, gouvernance.'],
        ['Transparence (art. 50)', 'L\'obligation d\'informer quand un contenu ou un échange implique une IA.'],
    ],
    'objectifs': [
        ['O1', 'Comprendre', 'Expliquer ce que fait un modèle de langage et ce qu\'il ne fait pas.', 'Les trois limites structurelles restituées en 2 minutes.'],
        ['O2', 'Appliquer', 'Formuler une demande complète : rôle, contexte, format, contrainte.', '6 demandes métier, dont 5 exploitables en 2 reprises maximum.'],
        ['O3', 'Analyser', 'Classer une information : je saisis / j\'anonymise d\'abord / je ne saisis jamais.', '« Le Tri de la Réserve » : 16 cartes sur 20.'],
        ['O4', 'Évaluer', 'Détecter une réponse fausse, inventée ou biaisée, et documenter la vérification.', '4 défauts identifiés sur 5, source citée.'],
        ['O5', 'Analyser', 'Déterminer si l\'assistant relié à l\'entreprise peut atteindre un document.', '« Qui voit quoi ? » : 8 cas sur 10.'],
        ['O6', 'Appliquer', 'Conduire un processus professionnel complet assisté par l\'IA.', 'Trois parcours au niveau « Acquis ».'],
        ['O7', 'Créer', 'Constituer une bibliothèque de demandes métier documentées.', '10 demandes passant le test du collègue.'],
        ['O8', 'Évaluer', 'Comparer une solution américaine et européenne sur un même besoin.', 'Arbitrage de 10 lignes : coût, souveraineté, dépendance, compétence.'],
        ['O9', 'Créer', 'Construire un assistant personnalisé réutilisable.', 'Assistant présenté en 3 minutes, limites énoncées.'],
        ['O10', 'Analyser', 'Auditer un tableau produit avec l\'IA.', '3 erreurs sur 4 détectées, méthode justifiée.'],
        ['O11', 'Appliquer', 'Appliquer la transparence (art. 50) et rédiger les mesures de gouvernance.', 'Deux mentions + trois mesures justifiées.'],
        ['O12', 'Créer', 'Constituer le dossier de preuve des mesures IA du poste.', 'Fiche de poste « usages IA » + plan à 30 jours signé.'],
    ],
    'jours_detail': [
        {
            'titre': 'Comprendre, demander, protéger',
            'fil': 'passer d\'un usage au hasard à des demandes qui fonctionnent, sur des données que l\'on a le droit de saisir.',
            'lignes': [
                ('08:00-10:00', '120 min', 'Comprendre (O1)', 'Séquence 0 : « qui a déjà collé un document client dans une IA ? » ; machine à probabilités ; trois limites : invention, date de connaissance, biais ; même question, trois outils.', 'Démonstration en direct + débat.', 'Trois outils projetés.'),
                PAUSE_MATIN,
                ('10:15-12:00', '105 min', 'Bien demander (O2)', 'Méthode des 4 C ; atelier « Mes 6 demandes métier » ; relancer plutôt que recommencer ; image et vidéo générées : ce qui engage l\'entreprise.', 'Atelier individuel sur son poste.', 'Fiche « 6 demandes ».'),
                DEJEUNER,
                ('13:00-13:15', '15 min', 'Réveil « Vrai ou inventé ? »', '8 affirmations, le groupe tranche.', 'Jeu collectif.', 'Cartes.'),
                ('13:15-15:00', '105 min', 'Garde-fous (O3)', '« Le Tri de la Réserve » : 20 cartes, trois bacs ; donnée personnelle, sensible, secret d\'affaires ; minimisation (art. 5), base légale (art. 6) ; comptes grand public contre professionnels ; anonymiser en trois gestes.', 'Jeu de tri en sous-groupes.', '20 cartes de données.'),
                PAUSE_APREM,
                ('15:15-17:00', '105 min', 'Vérifier, tracer, assumer (O4)', 'Atelier « Les 5 réponses ratées » ; première fiche de poste « usages IA » ; quiz d\'étape de 10 questions.', 'Diagnostic en binômes + quiz.', '5 réponses défaillantes.'),
            ],
            'livrables': ['6 demandes métier testées', 'tri des données maîtrisé', 'première fiche de poste « usages IA »'],
        },
        {
            'titre': 'Produire dans l\'entreprise',
            'fil': 'passer de demandes isolées à des processus entiers, dans la voie choisie, sans sur-partage.',
            'lignes': [
                ('08:00-10:00', '120 min', 'L\'assistant relié à l\'entreprise (O5)', 'Ce que l\'assistant voit déjà ; trois différences avec le grand public ; « Qui voit quoi ? » : 10 cas ; le sur-partage vient des droits, jamais de l\'IA.', 'Atelier en binômes.', 'Cartes « cas ».'),
                PAUSE_MATIN,
                ('10:15-12:00', '105 min', 'Deux voies, un même besoin (O8)', 'Voie américaine (Copilot, Gemini, Claude, ChatGPT) et européenne (Le Chat, Dust, Ollama) ; même compte rendu produit deux fois ; grille d\'arbitrage YEBA.', 'Démonstration à parité.', 'Postes des deux voies.'),
                DEJEUNER,
                ('13:00-13:15', '15 min', 'Réveil « Le relais de prompt »', 'Une demande améliorée de main en main.', 'Jeu collectif.', '-'),
                ('13:15-15:00', '105 min', 'Parcours métier complets (O6)', 'Du courriel client au devis sans ressaisie ; de la réunion au compte rendu relu ; du tableau brut à la synthèse pour la direction.', 'Atelier guidé, relecture tracée.', 'Documents fictifs de KAZ\'MARKET.'),
                PAUSE_APREM,
                ('15:15-17:00', '105 min', 'La bibliothèque de demandes (O7)', 'Demande réutilisable : objectif, limite, contrôle humain ; 10 demandes documentées ; le test du collègue.', 'Production + test croisé.', 'Gabarit de bibliothèque.'),
            ],
            'livrables': ['trois parcours métier', 'bibliothèque de 10 demandes', 'arbitrage américain / européen'],
        },
        {
            'titre': 'Automatiser et prouver',
            'fil': 'passer de l\'usage individuel à un assistant du poste et à des preuves que l\'entreprise peut montrer.',
            'lignes': [
                ('08:00-10:00', '120 min', 'Assistants personnalisés (O9)', 'Les 5 blocs de configuration ; agents Copilot, Gems, Projets Claude ou agents Mistral et Dust ; chacun construit l\'assistant de son poste.', 'Atelier long accompagné.', 'Licence nominative ou démonstration.'),
                PAUSE_MATIN,
                ('10:15-12:00', '105 min', 'Tableaux et données (O10)', '« Les 4 erreurs cachées » ; un chiffre qui part à la direction est recalculé à la main ; connecter l\'assistant à une base : ce que cela change juridiquement.', 'Audit individuel.', 'Tableau de bord piégé.'),
                DEJEUNER,
                ('13:00-13:15', '15 min', 'Réveil « L\'assistant qui ment »', 'Repérer l\'erreur volontaire.', 'Jeu collectif.', '-'),
                ('13:15-15:00', '105 min', 'Gouvernance (O11)', 'Éditeur sous-traitant (RGPD art. 28) ; localisation et transferts hors UE ; IA Act art. 4 et art. 50 ; trois mesures + dossier de preuve.', 'Apport + rédaction.', 'Modèles de mentions et de mesures.'),
                PAUSE_APREM,
                ('15:15-17:00', '105 min', 'Restitution et évaluation (O12)', 'Assistant présenté en 3 minutes ; mise en situation notée ; quiz final de 10 questions ; fiche de poste et plan à 30 jours signés.', 'Mise en situation notée.', 'Grille critériée, quiz.'),
            ],
            'livrables': ['assistant personnalisé', 'deux mentions de transparence', 'trois mesures de gouvernance', 'dossier de preuve'],
        },
    ],
    'moyens': MOYENS_BASE + [
        'Un poste connecté par participant, compte professionnel ; licences du jour 3 vérifiées par écrit lors de l\'entretien préalable.',
        'Environnement de démonstration fourni par YEBA FORMATIONS à défaut de licence.',
        'Fil rouge fictif : KAZ\'MARKET, supérette de Sainte-Clotilde, et sa centrale HYPER PÉI (entreprises fictives).',
    ],
    'grille': [
        ['1. Comprendre', 'Croyances erronées', 'Partiel', 'Trois limites expliquées', 'Exemples personnels'],
        ['2. Demander', 'Demandes vagues', 'Peu exploitables', '5 sur 6 exploitables', 'Réutilisables'],
        ['3. Tri des données', 'Saisie interdite', 'Erreurs', '16 sur 20', 'Justifie chaque cas'],
        ['4. Vérification', 'Aucune', 'Partielle', '4 défauts sur 5, source citée', 'Méthode systématique'],
        ['5. Droits d\'accès', 'Ignorés', 'Partiel', '8 cas sur 10', 'Propose une correction'],
        ['6. Parcours métier', 'Inachevés', 'Partiels', 'Trois parcours « Acquis »', 'Optimisés'],
        ['7. Bibliothèque', 'Absente', 'Personnelle', '10 demandes testées', 'Adoptée par l\'équipe'],
        ['8. Arbitrage', 'Absent', 'Préférence', 'Grille appliquée', 'Conditions de révision'],
        ['9. Assistant', 'Non fonctionnel', 'Fragile', 'Fonctionnel, limites énoncées', 'Testé par un collègue'],
        ['10. Audit de tableau', 'Aucune erreur vue', '1 ou 2', '3 sur 4', 'Méthode de contrôle écrite'],
        ['11. Transparence et gouvernance', 'Absentes', 'Incomplètes', 'Deux mentions + trois mesures', 'Plan de mise en œuvre'],
        ['12. Dossier de preuve', 'Absent', 'Incomplet', 'Fiche de poste + plan signé', 'Prêt pour un contrôle'],
    ],
    'seuil': '24/36 minimum, avec au moins 2/3 sur les critères 3, 4, 5 et 11. Les critères de conformité et de responsabilité ne se compensent pas.',
    'seuil_points': '24/36', 'critiques': '3, 4, 5 et 11',
    'suivi': suivi_standard(3, '« Mes 6 demandes », « Tri de la Réserve », « Qui voit quoi ? »', 'assistant et dossier de preuve'),
    'quiz': [
        ('Un modèle de langage est d\'abord…', ['A. une base de connaissances', 'B. une machine à probabilités qui prédit du texte', 'C. un moteur de recherche', 'D. un expert'], 'B', 'D\'où les inventions plausibles.'),
        ('Les 4 C d\'une demande sont…', ['A. Casquette, Contexte, Cadre, Contrôle', 'B. Court, Clair, Correct, Complet', 'C. Code, Clé, Compte, Copie', 'D. aucun'], 'A', 'La méthode enseignée en J1.'),
        ('Un contrat de travail nominatif se classe…', ['A. je saisis', 'B. j\'anonymise d\'abord ou je ne saisis jamais', 'C. au choix', 'D. je publie'], 'B', 'Minimisation et confidentialité.'),
        ('Vrai ou faux : un compte grand public gratuit offre les mêmes garanties qu\'un compte professionnel.', ['Vrai', 'Faux'], 'Faux', 'Les conditions d\'usage des saisies diffèrent.'),
        ('L\'IA cite une loi qui n\'existe pas. Que faire ?', ['A. La citer', 'B. Vérifier à la source officielle et corriger', 'C. Ignorer', 'D. Demander à une autre IA seulement'], 'B', 'La vérification se fait à la source.'),
        ('L\'assistant affiche un document RH confidentiel. Cause probable ?', ['A. Une panne', 'B. Des droits d\'accès trop larges', 'C. Un virus', 'D. L\'éditeur'], 'B', 'Le sur-partage vient des droits.'),
        ('Un chiffre produit avec l\'IA part à la direction. Règle ?', ['A. L\'envoyer', 'B. Le recalculer à la main', 'C. L\'arrondir', 'D. Le supprimer'], 'B', 'Règle YEBA.'),
        ('L\'article 50 de l\'IA Act impose…', ['A. d\'interdire l\'IA', 'B. d\'informer quand un contenu ou un échange implique une IA', 'C. d\'acheter une licence', 'D. rien'], 'B', 'Obligation de transparence.'),
        ('L\'éditeur de l\'outil d\'IA, pour vos données, est le plus souvent…', ['A. responsable de traitement', 'B. sous-traitant, avec un contrat (RGPD art. 28)', 'C. sans rôle', 'D. propriétaire'], 'B', 'Le contrat se vérifie.'),
        ('Que prouve le dossier de preuve des mesures IA ?', ['A. La conformité totale', 'B. Les mesures prises pour la maîtrise de l\'IA (art. 4)', 'C. La certification', 'D. Le diplôme'], 'B', 'Il documente des mesures, il ne certifie pas.'),
    ],
    'validation': [
        ['Comprendre et demander', '6 demandes + restitution', 'Production + oral', 'Score ≥ 2 aux critères 1 et 2'],
        ['Protéger et vérifier', 'Tri + 5 réponses ratées', 'Ateliers', 'Score ≥ 2 aux critères 3 et 4'],
        ['Produire dans l\'entreprise', 'Qui voit quoi + 3 parcours + bibliothèque', 'Ateliers', 'Score ≥ 2 aux critères 5 à 7'],
        ['Arbitrer et automatiser', 'Note + assistant + audit', 'Présentation', 'Score ≥ 2 aux critères 8 à 10'],
        ['Gouverner et prouver', 'Mentions, mesures, dossier', 'Dépôt', 'Score ≥ 2 aux critères 11 et 12'],
    ],
    'defi': {
        'intro': 'Vous présentez l\'assistant de votre poste et le dossier de preuve qui l\'accompagne.',
        'etapes': [
            'Présenter la tâche récurrente choisie et ce qu\'elle coûte aujourd\'hui.',
            'Montrer l\'assistant en fonctionnement et ses limites connues.',
            'Montrer ce qui ne sera jamais saisi et pourquoi.',
            'Présenter les deux mentions de transparence et les trois mesures de gouvernance.',
            'Signer la fiche de poste « usages IA » et le plan à 30 jours ; 3 minutes au total.',
        ],
    },
    'annexes': [
        {'titre': 'La méthode des 4 C', 'tableau': (['C', 'Ce que l\'on écrit'], [
            ['Casquette', 'Le rôle que doit prendre l\'IA : « Tu es assistant administratif d\'une PME réunionnaise ».'],
            ['Contexte', 'La situation, le destinataire, ce qui est déjà fait.'],
            ['Cadre', 'Le format, la longueur, le ton, ce qui est interdit.'],
            ['Contrôle', 'Ce que l\'IA doit signaler : manques, incertitudes, sources.'],
        ], [1, 3])},
        {'titre': 'Fiche de poste « usages IA » (modèle)', 'puces': [
            'Trois usages autorisés au poste, avec l\'outil et le compte utilisés.',
            'Pour chacun : la limite connue et le contrôle humain obligatoire.',
            'Ce qui ne se saisit jamais à ce poste.',
            'Mention de transparence utilisée quand un contenu est diffusé.',
            'Plan d\'action à 30 jours, signé par le stagiaire et son responsable.',
        ]},
    ],
    'accessibilite': 'Support projeté en corps 26, livret en corps 16 sur demande, contrastes WCAG 2.1, rythme adapté, pauses supplémentaires, consignes écrites, temps majoré pour les quiz, binômage sur les ateliers longs ; accessibilité du lieu vérifiée. Aucun aménagement facturé, aucune information médicale demandée.',
    'sources': [
        'Commission européenne, FAQ « Maîtrise de l\'IA » (art. 4) — https://digital-strategy.ec.europa.eu/fr/faqs/ai-literacy-questions-answers',
        'CNIL, questions-réponses sur l\'IA générative — https://www.cnil.fr/fr/les-questions-reponses-de-la-cnil-sur-lutilisation-dun-systeme-dia-generative',
        'Elements of AI (français) — https://www.elementsofai.fr/',
    ],
}
