from commun import DEJEUNER, MOYENS_BASE, PAUSE_APREM, PAUSE_MATIN, VERSION, suivi_standard

F = {
    'ref': 'FOR-0006', 'fichier': 'programme-detaille-for-0006-copilot-microsoft-365.pdf', 'nom_affiche': 'Programme detaille - FOR-0006 - Copilot Microsoft 365.pdf',
    'titre': "Copilot Microsoft 365 : Utiliser l'IA dans Word, Excel, Outlook et Teams (méthode des 4 P)",
    'nom': 'Copilot Microsoft 365',
    'promesse_titre': "Utiliser l'IA dans Word, Excel, Outlook et Teams, avec la méthode des 4 P",
    'promesse': "En deux jours, chaque participant apprend à savoir ce que Copilot voit, à formuler des demandes qui donnent un résultat exploitable, à traiter un processus métier complet et à prouver ce qui a été vérifié. Il repart avec un livrable réutilisable par son équipe et trois mesures de gouvernance rédigées.",
    'format_court': 'Présentiel - 2 jours', 'jours': 2, 'heures': 16, 'validation_courte': '1 livrable réutilisable',
    'inter': '790', 'intra': '2 500', 'version': VERSION,
    'public_court': 'salariés et dirigeants équipés de Microsoft 365 et de licences Copilot.',
    'public': 'Salariés et dirigeants équipés de Microsoft 365 qui produisent chaque semaine documents, analyses ou courriels (administratif, commercial, RH, encadrement, direction de TPE-PME). La journée 2 vise aussi la personne qui répond en interne à « est-ce qu\'on a le droit ? ».',
    'prerequis': 'Savoir créer un document, saisir des données dans un tableur et gérer sa messagerie. Conditions bloquantes vérifiées par écrit 5 jours ouvrés avant : poste à jour, compte nominatif avec licence Copilot active, documents professionnels réels accessibles, contact de l\'administrateur joignable. Sinon, la session est reportée.',
    'materiel': 'Poste à jour + compte nominatif avec licence Copilot active + documents professionnels réels, vérifiés par écrit 5 jours ouvrés avant.',
    'production': 'Bibliothèque de 5 demandes métier, trois parcours métier menés à terme, un livrable réutilisable présenté en 3 minutes et trois mesures de gouvernance argumentées.',
    'outils': 'Microsoft 365 Copilot dans Word, Excel, Outlook, Teams et PowerPoint ; documents réels de l\'entreprise.',
    'financements': 'OPCO, plan de développement des compétences, France Travail (AIF), Région Réunion',
    'positionnement': {
        'idee': "Copilot ne se pilote pas comme un outil grand public : il voit ce que vos droits d'accès lui permettent de voir. On commence donc par le Périmètre, puis le Prompt, la Production et la Preuve — la méthode des 4 P.",
        'intro': 'Les quatre domaines de la méthode :',
        'points': [
            'P1 Périmètre : ce que l\'assistant voit, à partir des droits déjà en place.',
            'P2 Prompt : une demande complète qui désigne ses sources.',
            'P3 Production : des processus entiers, d\'une application à l\'autre.',
            'P4 Preuve : vérifier, tracer et assumer ; tri des données ; gouvernance.',
        ],
        'vigilance': "Le sur-partage ne vient pas de l'IA mais des droits d'accès : un dossier ouvert à tous devient lisible par Copilot pour tous. On le vérifie avant de déployer.",
    },
    'vocabulaire': [
        ['Copilot', 'L\'assistant d\'IA de Microsoft 365, relié aux données de l\'entreprise auxquelles l\'utilisateur a accès.'],
        ['Périmètre', 'L\'ensemble des documents, courriels et réunions que l\'assistant peut atteindre.'],
        ['Droits d\'accès', 'Qui peut ouvrir quel fichier ; Copilot les respecte, il ne les corrige pas.'],
        ['Demande (prompt)', 'La consigne donnée à l\'assistant : objectif, contexte, sources, format.'],
        ['Source', 'Le document ou le courriel que l\'on désigne explicitement à Copilot.'],
        ['Hallucination', 'Une réponse plausible mais fausse ou inventée.'],
        ['Mention de transparence', 'L\'information donnée quand un contenu a été produit ou modifié par une IA (IA Act, art. 50).'],
        ['Gouvernance', 'Les règles écrites de l\'entreprise : qui peut faire quoi, avec quelles données, et comment on le prouve.'],
    ],
    'objectifs': [
        ['O1', 'Comprendre', 'Expliquer pourquoi un assistant relié aux données de l\'entreprise ne se pilote pas comme un outil grand public.', 'Restitution orale de 3 minutes : 3 différences sur 3.'],
        ['O2', 'Analyser', 'Déterminer si l\'assistant peut atteindre un document, à partir des droits en place.', 'Atelier « Qui voit quoi ? » : 8 cas sur 10.'],
        ['O3', 'Appliquer', 'Construire une demande complète en désignant les sources.', '5 demandes testées, dont 4 exploitables en 2 reprises maximum.'],
        ['O4', 'Évaluer', 'Diagnostiquer une réponse décevante et choisir le correctif adapté.', '3 diagnostics corrects sur 4.'],
        ['O5', 'Appliquer', 'Conduire un processus complet en enchaînant plusieurs applications.', 'Trois parcours métier au niveau « Acquis ».'],
        ['O6', 'Créer', 'Concevoir un livrable réutilisable par d\'autres.', 'Livrable fonctionnel présenté en 3 minutes, limites énoncées.'],
        ['O7', 'Analyser', 'Classer une information : je saisis / j\'anonymise d\'abord / je ne saisis jamais.', '« Le Tri de la Réserve » : 16 cartes sur 20.'],
        ['O8', 'Évaluer', 'Argumenter trois mesures de gouvernance pour sa structure.', 'Trois mesures, dont une sur les droits d\'accès et une sur la localisation des traitements.'],
    ],
    'jours_detail': [
        {
            'titre': 'Périmètre et Prompt',
            'fil': 'savoir ce que Copilot voit, puis lui demander ce qu\'il faut, sur ses vrais documents.',
            'lignes': [
                ('08:00-08:30', '30 min', 'Séquence 0 « La question qui dérange »', 'Qui a déjà demandé à une IA ce qu\'elle sait de son entreprise ? Attentes ; information RGPD et transparence IA.', 'Tour de table + affichage des attentes.', 'Diaporama.'),
                ('08:30-09:15', '45 min', 'Ce qui change avec Copilot (O1)', 'IA générative sans jargon ; ce qui change quand elle est reliée aux données de l\'entreprise.', 'Démonstration comparée grand public / Copilot.', 'Poste formateur, comptes de démonstration.'),
                ('09:15-10:00', '45 min', 'P1 — Qui voit quoi ? (O2)', 'Droits de partage, équipes, sites ; 10 cas de documents à qualifier.', 'Atelier en binômes.', 'Cartes « cas », schéma des droits.'),
                PAUSE_MATIN,
                ('10:15-11:00', '45 min', 'P2 — La demande complète (O3)', 'Objectif, contexte, sources désignées, format attendu.', 'Démonstration puis pratique.', 'Word, Outlook avec Copilot.'),
                ('11:00-12:00', '60 min', 'Mes 5 demandes métier (O3)', 'Cinq demandes testées sur ses propres documents ; fiche de résultats.', 'Pratique individuelle accompagnée.', 'Fiche « Mes 5 demandes métier ».'),
                DEJEUNER,
                ('13:00-14:00', '60 min', 'Quand la réponse ne convient pas (O4)', 'Les quatre correctifs : contexte, exemple, périmètre, question en retour ; atelier « Les 4 réponses ratées ».', 'Étude de cas + diagnostic en binômes.', '4 réponses défaillantes fournies.'),
                ('14:00-15:00', '60 min', 'La consigne permanente', 'Instructions réutilisables et bibliothèque de demandes de l\'équipe.', 'Atelier guidé.', 'Gabarit de bibliothèque.'),
                PAUSE_APREM,
                ('15:15-16:30', '75 min', 'Atelier « L\'échange difficile »', 'Courriel délicat, compte rendu, réponse à une réclamation : produire, relire, assumer.', 'Pratique + revue par les pairs.', 'Outlook, Word, Teams.'),
                ('16:30-17:00', '30 min', 'Bilan et défi au poste (O1)', 'Restitution des 3 différences ; défi à réaliser au poste avant J2.', 'Restitution orale.', 'Fiche défi.'),
            ],
            'livrables': ['fiche « Mes 5 demandes métier »', 'premières entrées de la bibliothèque de demandes'],
        },
        {
            'titre': 'Production et Preuve',
            'fil': 'traiter des processus entiers, puis prouver ce qui a été vérifié et ce qui ne doit jamais être saisi.',
            'lignes': [
                ('08:00-08:30', '30 min', 'Le mur des retours', 'Retour sur les défis au poste ; quiz de réactivation.', 'Partage + quiz oral.', 'Paperboard.'),
                ('08:30-10:00', '90 min', 'P3 — Parcours 1 et 2 (O5)', 'Le dossier client de A à Z (Word, Outlook) ; la réunion Teams qui laisse une trace.', 'Atelier guidé, relecture humaine tracée.', 'Word, Outlook, Teams.'),
                PAUSE_MATIN,
                ('10:15-11:15', '60 min', 'P3 — Parcours 3 : le point mensuel chiffré (O5)', 'Excel avec Copilot : analyser, synthétiser, recalculer chaque chiffre à la main.', 'Pratique individuelle.', 'Excel, tableau fictif.'),
                ('11:15-12:00', '45 min', 'Livrable réutilisable (O6)', 'Modèle, consigne ou procédure que l\'équipe pourra réutiliser.', 'Conception individuelle accompagnée.', 'Gabarit de livrable.'),
                DEJEUNER,
                ('13:00-13:45', '45 min', 'P4 — Le Tri de la Réserve (O7)', '20 cartes : je saisis / j\'anonymise / je ne saisis jamais ; RGPD art. 5 et 6.', 'Jeu de tri en sous-groupes.', '20 cartes de données.'),
                ('13:45-15:00', '75 min', 'P4 — Gouvernance (O8)', 'Charte d\'usage, maîtrise de l\'IA (IA Act art. 4), transparence (art. 50), sous-traitance (RGPD art. 28), localisation des traitements.', 'Apport court + rédaction des 3 mesures.', 'Modèle de charte.'),
                PAUSE_APREM,
                ('15:15-16:15', '60 min', 'Évaluation finale', 'Processus complet sur cas concret, vérification documentée ; quiz de 10 questions.', 'Mise en situation notée.', 'Grille critériée, quiz.'),
                ('16:15-17:00', '45 min', 'Présentation des livrables et ancrage (O6)', '3 minutes par stagiaire ; plan d\'ancrage ; satisfaction.', 'Restitution + engagement écrit.', 'Fiche d\'ancrage.'),
            ],
            'livrables': ['trois parcours métier menés à terme', 'livrable réutilisable', 'trois mesures de gouvernance'],
        },
    ],
    'moyens': MOYENS_BASE + [
        'Un poste par participant, compte nominatif et licence Copilot active (vérification écrite J-5).',
        'Documents professionnels réels accessibles, et documents fictifs de secours.',
        'Contact de l\'administrateur Microsoft 365 du client joignable pendant la session.',
    ],
    'grille': [
        ['1. Périmètre', 'Ignore ce que l\'outil voit', 'Notion partielle', '8 cas sur 10 corrects', 'Propose une correction des droits'],
        ['2. Demande', 'Vague', 'Sans source', 'Complète, sources désignées', 'Réutilisable par l\'équipe'],
        ['3. Correctifs', 'Recommence au hasard', 'Un correctif', 'Bon correctif choisi', 'Explique le choix'],
        ['4. Parcours métier', 'Inachevé', 'Partiel', 'Trois parcours menés à terme', 'Enchaînement optimisé'],
        ['5. Vérification', 'Aucune', 'Partielle', 'Chaque chiffre recontrôlé', 'Trace de vérification conservée'],
        ['6. Tri des données', 'Saisie de données interdites', 'Erreurs', '16 cartes sur 20', 'Justifie chaque cas'],
        ['7. Livrable', 'Absent', 'Personnel', 'Réutilisable, limites énoncées', 'Testé par un collègue'],
        ['8. Gouvernance', 'Absente', 'Mesures vagues', 'Trois mesures justifiées', 'Plan de mise en œuvre daté'],
    ],
    'seuil': '16/24 minimum, avec au moins 2/3 sur les critères 1, 5 et 6. On ne compense pas un risque juridique par de la productivité.',
    'seuil_points': '16/24', 'critiques': '1, 5 et 6',
    'suivi': suivi_standard(2, '« Qui voit quoi ? », « Mes 5 demandes », « Les 4 réponses ratées »', 'livrable et processus complet'),
    'quiz': [
        ('Pourquoi Copilot peut-il citer un document que vous n\'avez jamais ouvert ?', ['A. Il invente', 'B. Vos droits d\'accès vous permettent de l\'atteindre', 'C. Microsoft l\'a ajouté', 'D. C\'est impossible'], 'B', 'Copilot respecte les droits existants : s\'ils sont trop larges, il voit trop.'),
        ('Le sur-partage vient…', ['A. de l\'IA', 'B. des droits d\'accès mal réglés', 'C. du réseau', 'D. de l\'utilisateur seul'], 'B', 'On corrige les droits, pas l\'IA.'),
        ('Une demande complète désigne notamment…', ['A. la couleur du document', 'B. les sources à exploiter', 'C. le prix de la licence', 'D. rien de plus'], 'B', 'Désigner les sources réduit les erreurs.'),
        ('La réponse est trop générale. Premier correctif ?', ['A. Changer d\'outil', 'B. Ajouter du contexte', 'C. Abandonner', 'D. Copier-coller ailleurs'], 'B', 'Le manque de contexte est la cause la plus fréquente.'),
        ('Un total produit par Copilot dans Excel part à la direction. Que faire ?', ['A. L\'envoyer', 'B. Le recalculer à la main', 'C. L\'arrondir', 'D. Le mettre en gras'], 'B', 'Un chiffre qui part à la direction est un chiffre recontrôlé.'),
        ('Un numéro de sécurité sociale de salarié se classe…', ['A. je saisis', 'B. j\'anonymise d\'abord', 'C. je ne saisis jamais', 'D. au choix'], 'C', 'Donnée particulièrement sensible : jamais dans une demande.'),
        ('Vrai ou faux : un compte personnel gratuit peut remplacer le compte professionnel en formation.', ['Vrai', 'Faux'], 'Faux', 'Les conditions de traitement des données ne sont pas les mêmes.'),
        ('L\'IA Act, article 4, demande à l\'employeur…', ['A. de prendre des mesures pour favoriser la maîtrise de l\'IA de son personnel', 'B. d\'interdire l\'IA', 'C. d\'acheter Copilot', 'D. rien'], 'A', 'La formation est l\'une de ces mesures, à documenter.'),
        ('L\'éditeur de l\'assistant traite vos données pour votre compte. Que vérifier ?', ['A. Son logo', 'B. Le contrat de sous-traitance (RGPD art. 28) et la localisation des traitements', 'C. Son cours de bourse', 'D. Rien'], 'B', 'C\'est une mesure de gouvernance à écrire.'),
        ('Un compte rendu Teams généré par Copilot doit être…', ['A. diffusé tel quel', 'B. relu par un humain avant diffusion', 'C. supprimé', 'D. traduit'], 'B', 'La relecture humaine tracée est une preuve de maîtrise.'),
    ],
    'validation': [
        ['Comprendre le périmètre', 'Restitution + « Qui voit quoi ? »', 'Oral + atelier', 'Score ≥ 2 au critère 1'],
        ['Formuler et corriger', 'Fiche 5 demandes + diagnostics', 'Production', 'Score ≥ 2 aux critères 2 et 3'],
        ['Produire un processus', 'Trois parcours', 'Mise en situation', 'Score ≥ 2 aux critères 4 et 5'],
        ['Protéger les données', 'Tri de la Réserve', 'Atelier', 'Score ≥ 2 au critère 6'],
        ['Concevoir et gouverner', 'Livrable + 3 mesures', 'Présentation', 'Score ≥ 2 aux critères 7 et 8'],
    ],
    'defi': {
        'intro': 'Vous traitez un processus réel de votre poste, ou le cas de secours : la réponse à une réclamation client d\'une agence de voyages de Saint-Denis, du courriel reçu au compte rendu au responsable.',
        'etapes': [
            'Vérifier ce que Copilot peut atteindre pour ce cas, et l\'expliquer.',
            'Formuler les demandes en désignant les sources.',
            'Produire le courriel de réponse, le compte rendu et le tableau de suivi.',
            'Montrer ce que vous avez vérifié et ce que vous avez écarté, par écrit.',
            'Présenter votre livrable réutilisable et ses limites en 3 minutes.',
        ],
    },
    'annexes': [
        {'titre': 'La méthode des 4 P en une page', 'tableau': (['Domaine', 'Question à se poser'], [
            ['P1 Périmètre', 'Que peut voir l\'assistant pour cette tâche, et est-ce normal ?'],
            ['P2 Prompt', 'Ai-je donné l\'objectif, le contexte, les sources et le format ?'],
            ['P3 Production', 'Quelles applications s\'enchaînent, et où se fait la relecture humaine ?'],
            ['P4 Preuve', 'Qu\'ai-je vérifié, qu\'ai-je écarté, et puis-je le montrer ?'],
        ], [1, 3])},
        {'titre': 'Les trois mesures de gouvernance (modèle)', 'puces': [
            'Droits d\'accès : revue des dossiers partagés avant tout déploiement, puis tous les six mois, par un responsable nommé.',
            'Localisation des traitements : vérifier dans le contrat la région de traitement et les transferts hors UE ; consigner la réponse.',
            'Usages : charte d\'une page — ce qui est permis, ce qui ne se saisit jamais, qui arbitre, mention de transparence quand un contenu est diffusé.',
        ]},
    ],
    'accessibilite': 'Formation accessible aux personnes en situation de handicap ; aucun justificatif médical n\'est demandé. Spécifique : poste adapté (loupe d\'écran, dictée vocale, clavier et souris ergonomiques) ; les fonctions d\'accessibilité de Microsoft 365 sont présentées en séance ; la restitution de 3 minutes peut être remplacée par une remise écrite commentée.',
    'sources': [
        'Microsoft Learn, « Microsoft 365 Copilot » — https://learn.microsoft.com/fr-fr/copilot/microsoft-365/',
        'CNIL, questions-réponses sur l\'IA générative — https://www.cnil.fr/fr/les-questions-reponses-de-la-cnil-sur-lutilisation-dun-systeme-dia-generative',
        'Règlement (UE) 2024/1689 (IA Act), articles 4 et 50 — https://eur-lex.europa.eu/',
    ],
}
