from commun import DEJEUNER, MOYENS_BASE, PAUSE_APREM, PAUSE_MATIN, VERSION, suivi_standard

F = {
    'ref': 'FOR-0013', 'fichier': 'programme-detaille-for-0013-agents-ia.pdf', 'nom_affiche': 'Programme detaille - FOR-0013 - Agents IA.pdf',
    'titre': "Agents IA : Déléguer des tâches à l'IA sous contrôle humain (niveau avancé, 2 jours)",
    'nom': 'Agents IA',
    'promesse_titre': "Déléguer des tâches à l'IA sous contrôle humain — niveau avancé",
    'promesse': "En deux jours, chaque participant met en service un agent qui exécute une tâche réelle, construit une chaîne de deux agents avec point d'arrêt humain, en trace chaque décision et repart avec une procédure d'arrêt d'urgence testée par un autre stagiaire.",
    'format_court': 'Présentiel - 2 jours', 'jours': 2, 'heures': 16, 'validation_courte': 'Chaîne d\'agents démontrée',
    'inter': '990', 'intra': '2 900', 'version': VERSION,
    'public_court': 'dirigeants, responsables informatiques, référents IA et chefs de projet à l\'usage avancé de l\'IA.',
    'public': 'Dirigeants, responsables informatiques, référents IA, chefs de projet et profils techniques ayant un usage avancé de l\'IA générative ou ayant suivi « IA générative au travail ». La journée 2 vise aussi la personne qui répond en interne à « qui est responsable ? ».',
    'prerequis': 'Usage avancé de l\'IA générative. Aucune programmation exigée, mais accepter de travailler dans un terminal. Poste avec droits d\'installation (ou machine virtuelle fournie). Checklist technique transmise 10 jours avant ; entretien de cadrage de 20 minutes avec le responsable.',
    'materiel': 'Poste avec droits d\'installation (ou machine virtuelle fournie). Checklist technique envoyée 10 jours avant.',
    'production': 'Un agent en service sur une tâche délimitée, une chaîne de deux agents avec validation humaine, un journal d\'exécution, une procédure d\'arrêt d\'urgence testée et une note d\'arbitrage d\'architecture.',
    'outils': 'Voie américaine : Claude Code, Codex. Voie européenne : Mistral Vibe CLI et Devstral, modèle local avec Ollama, n8n auto-hébergé.',
    'financements': 'OPCO, plan de développement des compétences, France Travail (AIF), Région Réunion',
    'positionnement': {
        'idee': "Un agent n'est pas un assistant plus rapide : il agit. On ne lui donne donc d'autonomie qu'à hauteur du coût de son erreur, on trace ce qu'il fait et l'on sait l'arrêter.",
        'intro': 'Chaque atelier est conduit dans les deux voies, puis comparé :',
        'points': [
            'Qualifier : assistant, agent ou système, et ce que chacun décide seul.',
            'Mettre en service un agent sur un périmètre délimité, avec ses règles et ses autorisations.',
            'Chaîner deux agents avec un point de contrôle humain obligatoire.',
            'Tracer : qui a décidé, quand, sur quelle donnée.',
            'Arrêter : procédure d\'urgence et reprise manuelle, testées.',
        ],
        'vigilance': "Un agent mal encadré produit un dommage réel : boucle infinie, dérive de consigne, facturation qui s'emballe. Les plafonds de consommation et l'arrêt d'urgence se posent avant la première exécution.",
    },
    'vocabulaire': [
        ['Agent', 'Une IA qui exécute une suite d\'actions pour atteindre un but, et pas seulement une réponse.'],
        ['Système multi-agents', 'Plusieurs agents qui se transmettent un travail.'],
        ['Fichier d\'instructions', 'Les règles permanentes données à l\'agent avant qu\'il agisse.'],
        ['Autorisations', 'Ce que l\'agent peut faire sans demander, et ce qui exige un accord.'],
        ['Déclencheur', 'Ce qui lance l\'agent sans humain devant : horaire, événement, message.'],
        ['Journal d\'exécution', 'La trace lisible de ce que l\'agent a fait, pour quelqu\'un qui n\'était pas là.'],
        ['Arrêt d\'urgence', 'La procédure qui stoppe l\'agent et rend la main à un humain.'],
        ['Dérive de consigne', 'Quand l\'agent s\'éloigne peu à peu de la tâche demandée.'],
    ],
    'objectifs': [
        ['O1', 'Comprendre', 'Distinguer assistant, agent et système multi-agents, et ce que chacun peut décider seul.', 'Atelier de qualification : 9 situations sur 10.'],
        ['O2', 'Appliquer', 'Mettre en service un agent qui exécute une tâche de bout en bout sur un périmètre délimité.', 'Trois exécutions de suite sans intervention en fin de J1.'],
        ['O3', 'Créer', 'Concevoir une chaîne de deux agents avec un point de contrôle humain obligatoire.', 'Chaîne opérationnelle avec validation humaine explicite.'],
        ['O4', 'Évaluer', 'Fixer le niveau d\'autonomie acceptable au regard du risque.', '5 scénarios justifiés sur 6.'],
        ['O5', 'Analyser', 'Établir la traçabilité : qui a décidé, quand, sur quelle donnée.', 'Journal d\'exécution avec responsable de chaque décision.'],
        ['O6', 'Évaluer', 'Qualifier un système au regard de l\'IA Act.', '7 cas corrects sur 8, article cité.'],
        ['O7', 'Créer', 'Rédiger la procédure d\'arrêt d\'urgence et de reprise manuelle.', 'Procédure testée par un stagiaire qui n\'a pas construit l\'agent.'],
        ['O8', 'Évaluer', 'Arbitrer entre architecture américaine et européenne.', 'Note citant coût, souveraineté, réversibilité, compétence, continuité.'],
    ],
    'jours_detail': [
        {
            'titre': 'Mettre en service un agent',
            'fil': 'passer d\'un assistant qui répond à un agent qui exécute, dans les deux voies, avec un niveau d\'autonomie justifié.',
            'lignes': [
                ('08:00-10:00', '120 min', 'Qualification (O1)', 'Séquence 0 : un agent qui agit seul 4 minutes ; assistant, agent, système ; 10 situations à qualifier ; que se passe-t-il si l\'agent se trompe et que personne ne regarde ?', 'Démonstration + atelier de qualification.', 'Cartes « situations ».'),
                PAUSE_MATIN,
                ('10:15-12:00', '105 min', 'Premier agent, voie américaine (O2)', 'Agent dans le terminal : ce qu\'il lit, écrit, exécute ; fichier d\'instructions ; autorisations ; mise en service sur une tâche délimitée.', 'Démonstration puis atelier.', 'Claude Code ou Codex, dossier de travail fictif.'),
                DEJEUNER,
                ('13:00-13:15', '15 min', 'Réveil « L\'agent sans garde-fou »', 'Ce qui aurait pu mal tourner ce matin.', 'Oral collectif.', '-'),
                ('13:15-15:00', '105 min', 'Premier agent, voie européenne (O2, O8)', 'Mistral Vibe CLI et Devstral sous licence ouverte ; modèle local avec Ollama ; n8n auto-hébergé ; même tâche, puis comparaison.', 'Atelier comparé.', 'Vibe CLI, Ollama, n8n.'),
                PAUSE_APREM,
                ('15:15-17:00', '105 min', 'Autonomie et risque (O4, O5)', 'Quatre niveaux d\'autonomie ; atelier « Jusqu\'où ? » sur 6 scénarios ; journal d\'exécution lisible ; agent qui tourne trois fois sans intervention.', 'Atelier + validation de l\'agent.', 'Fiche scénarios, modèle de journal.'),
            ],
            'livrables': ['agent en service (3 exécutions)', 'niveaux d\'autonomie justifiés', 'premier journal d\'exécution'],
        },
        {
            'titre': 'Chaîner, encadrer, arbitrer',
            'fil': 'faire travailler deux agents ensemble sans perdre le contrôle, puis prouver qui répond de quoi.',
            'lignes': [
                ('08:00-10:00', '120 min', 'Chaînes d\'agents (O3)', 'Passage de relais et point de rupture ; où placer le contrôle humain ; construire une chaîne avec arrêt de validation ; boucle infinie, dérive, donnée absente.', 'Atelier long accompagné.', 'Outils des deux voies.'),
                PAUSE_MATIN,
                ('10:15-12:00', '105 min', 'L\'IA qui travaille seule (O7)', 'Déclencheurs ; exécution programmée avec compte rendu obligatoire ; procédure d\'arrêt d\'urgence rédigée puis testée par un autre stagiaire ; plafonds de consommation.', 'Atelier + test croisé.', 'Modèle de procédure.'),
                DEJEUNER,
                ('13:00-13:15', '15 min', 'Réveil « Qui signe ? »', 'Trois questions de reprise.', 'Oral collectif.', '-'),
                ('13:15-15:00', '105 min', 'Qualification juridique et gouvernance (O6)', 'IA Act : interdit (art. 5), haut risque (annexe III), transparence (art. 50) ; le piège RH ; RGPD art. 22 ; 8 cas ; dossier de preuve.', 'Atelier de qualification.', 'Fiches cas, textes officiels.'),
                PAUSE_APREM,
                ('15:15-17:00', '105 min', 'Arbitrage et évaluation (O8)', 'Note d\'arbitrage sur un cas réel ; restitution de 5 minutes, chaîne démontrée en direct ; quiz de 10 questions.', 'Mise en situation notée.', 'Grille critériée, quiz.'),
            ],
            'livrables': ['chaîne de deux agents', 'procédure d\'arrêt testée', 'kit de gouvernance', 'note d\'arbitrage'],
        },
    ],
    'moyens': MOYENS_BASE + [
        'Postes avec droits d\'installation ou machines virtuelles ; débit réseau vérifié sur le lieu.',
        'Comptes et clés d\'accès aux outils retenus, avec plafonds de consommation posés avant la session.',
        'Dossiers de travail fictifs (commandes et réclamations de KAZ\'MARKET, entreprise fictive).',
    ],
    'grille': [
        ['1. Qualification', 'Confusion', 'Partielle', '9 situations sur 10', 'Explique les cas limites'],
        ['2. Périmètre et autorisations', 'Agent sans limites', 'Limites floues', 'Périmètre et autorisations écrits', 'Moindre privilège appliqué'],
        ['3. Agent en service', 'Non fonctionnel', 'Avec interventions', 'Trois exécutions sans intervention', 'Robuste aux cas limites'],
        ['4. Chaîne et contrôle humain', 'Pas de contrôle', 'Contrôle mal placé', 'Validation avant l\'action irréversible', 'Contrôle utile et rapide'],
        ['5. Autonomie', 'Au confort', 'Sans justification', '5 scénarios sur 6', 'Coût de l\'erreur chiffré'],
        ['6. Traçabilité', 'Aucune', 'Journal illisible', 'Journal + responsable par décision', 'Lisible par un tiers'],
        ['7. Arrêt d\'urgence', 'Absent', 'Non testé', 'Testé par un autre stagiaire', 'Reprise manuelle fluide'],
        ['8. Qualification juridique', 'Erreurs majeures', 'Sans article', '7 cas sur 8, article cité', 'Anticipe les obligations'],
    ],
    'seuil': '16/24 minimum, avec au moins 2/3 sur les critères 2, 4, 6, 7 et 8. On ne compense pas un risque réel par de la performance technique.',
    'seuil_points': '16/24', 'critiques': '2, 4, 6, 7 et 8',
    'suivi': suivi_standard(2, 'Qualification, agent en service, « Jusqu\'où ? »', 'chaîne démontrée'),
    'quiz': [
        ('Qu\'est-ce qui distingue un agent d\'un assistant ?', ['A. Il est plus rapide', 'B. Il exécute des actions, pas seulement des réponses', 'C. Il est gratuit', 'D. Il parle plusieurs langues'], 'B', 'L\'agent agit : c\'est ce qui change le risque.'),
        ('Où placer le point de contrôle humain d\'une chaîne ?', ['A. À la fin', 'B. Avant la première action irréversible', 'C. Au hasard', 'D. Nulle part'], 'B', 'Un contrôle après le dommage ne sert à rien.'),
        ('Le niveau d\'autonomie se fixe sur…', ['A. le confort d\'usage', 'B. le coût de l\'erreur', 'C. la vitesse', 'D. le prix'], 'B', 'Règle YEBA.'),
        ('Que doit permettre le journal d\'exécution ?', ['A. Décorer', 'B. Savoir qui a décidé, quand, sur quelle donnée', 'C. Facturer', 'D. Rien'], 'B', 'La traçabilité est une preuve.'),
        ('Vrai ou faux : la procédure d\'arrêt d\'urgence peut être testée par celui qui a construit l\'agent seulement.', ['Vrai', 'Faux'], 'Faux', 'Elle doit être exécutable par quelqu\'un d\'autre.'),
        ('Avant la première exécution d\'un agent facturé à l\'usage, il faut…', ['A. rien', 'B. poser des plafonds de consommation', 'C. augmenter le budget', 'D. désactiver les alertes'], 'B', 'La dérive de consommation est un risque réel.'),
        ('Un agent qui trie les candidatures relève…', ['A. du haut risque (annexe III)', 'B. d\'aucune règle', 'C. des pratiques interdites', 'D. du RGPD seulement'], 'A', 'Le piège des ressources humaines.'),
        ('Une décision produisant un effet juridique sur une personne…', ['A. peut être entièrement automatisée', 'B. ne peut pas être entièrement automatisée sans garanties (RGPD art. 22)', 'C. est interdite', 'D. relève de l\'éditeur'], 'B', 'Intervention humaine et droit de contester.'),
        ('Qu\'apporte un modèle local avec Ollama dans la démonstration ?', ['A. Plus de vitesse', 'B. Zéro donnée sortante', 'C. Plus de fonctions', 'D. Rien'], 'B', 'Voie européenne et souveraine.'),
        ('Qu\'appelle-t-on dérive de consigne ?', ['A. Un bug d\'affichage', 'B. L\'agent qui s\'éloigne peu à peu de la tâche', 'C. Un changement de prix', 'D. Une mise à jour'], 'B', 'D\'où les instructions permanentes et le contrôle humain.'),
    ],
    'validation': [
        ['Qualifier', 'Atelier de qualification', 'Atelier', 'Score ≥ 2 au critère 1'],
        ['Mettre en service', 'Agent + autorisations', 'Démonstration', 'Score ≥ 2 aux critères 2 et 3'],
        ['Chaîner sous contrôle', 'Chaîne de deux agents', 'Démonstration en direct', 'Score ≥ 2 aux critères 4 et 5'],
        ['Tracer et arrêter', 'Journal + procédure testée', 'Test croisé', 'Score ≥ 2 aux critères 6 et 7'],
        ['Qualifier et arbitrer', '8 cas + note', 'Dépôt + restitution', 'Score ≥ 2 au critère 8'],
    ],
    'defi': {
        'intro': 'Vous démontrez une chaîne d\'agents sur un cas réel de votre entreprise, ou sur le flux de réclamations de KAZ\'MARKET (entreprise fictive).',
        'etapes': [
            'Présenter la tâche, le périmètre et les autorisations de chaque agent.',
            'Exécuter la chaîne en direct, jusqu\'au point de validation humaine.',
            'Montrer le journal d\'exécution et le responsable de chaque décision.',
            'Faire exécuter la procédure d\'arrêt par un autre stagiaire.',
            'Présenter l\'arbitrage d\'architecture en 5 minutes au total.',
        ],
    },
    'annexes': [
        {'titre': 'Kit de gouvernance des agents', 'tableau': (['Pièce', 'Contenu'], [
            ['Fiche d\'inventaire', 'Nom de l\'agent, tâche, outils, données, voie technique.'],
            ['Niveau d\'autonomie', 'Niveau retenu et justification par le coût de l\'erreur.'],
            ['Journal d\'exécution type', 'Horodatage, action, donnée, décision, responsable.'],
            ['Procédure d\'arrêt', 'Comment arrêter, qui prévenir, comment reprendre à la main.'],
            ['Qualification', 'Régime IA Act et article ; RGPD art. 22 le cas échéant.'],
        ], [1, 3])},
        {'titre': 'Procédure d\'arrêt d\'urgence (trame)', 'puces': [
            'Signes qui imposent l\'arrêt (boucle, dérive, coût anormal, plainte).',
            'Geste d\'arrêt immédiat, décrit écran par écran.',
            'Personnes à prévenir et dans quel ordre.',
            'Reprise manuelle des tâches en cours.',
            'Analyse de l\'incident et conditions de redémarrage.',
        ]},
    ],
    'accessibilite': 'Support projeté en corps 26 minimum, livret en corps 16 sur demande, terminal en fort contraste et corps majoré, rythme adapté, pauses supplémentaires, consignes écrites, temps majoré pour le quiz, binômage sur les ateliers techniques. Aucun aménagement n\'est facturé.',
    'sources': [
        'Mistral AI, « Devstral 2 et Vibe CLI » — https://mistral.ai/news/devstral-2-vibe-cli/',
        'n8n, agents IA et auto-hébergement — https://docs.n8n.io/advanced-ai/',
        'Règlement (UE) 2024/1689 (IA Act), art. 5, 50 et annexe III ; RGPD art. 22 — https://eur-lex.europa.eu/',
    ],
}
