from commun import DEJEUNER, MOYENS_BASE, PAUSE_APREM, PAUSE_MATIN, VERSION, suivi_standard

F = {
    'ref': 'FOR-0009', 'fichier': 'programme-detaille-for-0009-site-internet-ia.pdf', 'nom_affiche': 'Programme detaille - FOR-0009 - Site internet IA.pdf',
    'titre': 'Site internet IA : Créer son site en le décrivant à voix haute',
    'nom': 'Site internet IA',
    'promesse_titre': 'Créer son site en le décrivant à voix haute',
    'promesse': "À 17h00, chaque participant repart avec son site en ligne, juridiquement conforme, construit à partir de sa propre description orale, et la fiche « faire évoluer mon site » pour le tenir seul, sans prestataire.",
    'format_court': 'Présentiel - 1 jour', 'jours': 1, 'heures': 8, 'validation_courte': '1 site publié',
    'inter': '790', 'intra': '2 500', 'version': VERSION,
    'public_court': 'artisans, commerçants, indépendants et créateurs d\'entreprise sans site ou dépendants d\'un prestataire.',
    'public': 'Dirigeants de TPE, artisans, commerçants, indépendants et créateurs d\'entreprise sans site internet, ou dont le site ne peut pas évoluer sans prestataire. Convient aussi aux fonctions administratives chargées de faire vivre le site d\'une petite structure.',
    'prerequis': 'Utilisation courante d\'un ordinateur, d\'un navigateur et d\'une messagerie. Aucune compétence en développement, graphisme ou référencement. Venir avec son projet réel : activité, tarifs, photos, textes existants.',
    'materiel': 'Un ordinateur portable par stagiaire (inter : apporter le sien). Micro-casque fourni. Apporter ses textes, photos et tarifs.',
    'production': 'Un site de 3 à 5 pages publié, avec mentions légales, politique de confidentialité, gestion des traceurs et contrôles d\'accessibilité de base, plus la fiche « faire évoluer mon site ».',
    'outils': 'Générateur de site piloté par la voix ou le texte (choisi selon le coût réel, l\'hébergement des données et la réversibilité), dictée vocale, assistant d\'IA en compte professionnel.',
    'financements': 'OPCO, plan de développement des compétences, Région Réunion, France Travail (AIF)',
    'positionnement': {
        'idee': "Le site se construit en le décrivant : on apprend à dire clairement ce que l'on vend, à qui et ce que le visiteur doit faire, puis l'outil génère et l'on corrige. La compétence évaluée est la structuration de la demande, pas la technique.",
        'intro': 'La journée suit quatre gestes :',
        'points': [
            'Dire : les quatre phrases d\'un site utile et l\'arborescence de 3 à 5 pages.',
            'Piloter : générer, puis corriger par itérations avec les quatre leviers.',
            'Produire : textes, titres, images légales, page contact minimale.',
            'Publier en conformité et savoir faire évoluer le site seul.',
        ],
        'vigilance': "Un générateur invente volontiers des tarifs, des horaires ou des labels. Tout ce que l'outil a écrit sans qu'on le lui dise est surligné et vérifié avant publication : une allégation fausse est une pratique commerciale trompeuse.",
    },
    'vocabulaire': [
        ['Arborescence', 'La liste des pages du site et leur ordre.'],
        ['Cahier des charges', 'Ce que le site doit dire et faire, formulé avant de le construire.'],
        ['Nom de domaine', 'L\'adresse du site ; il doit être enregistré au nom de l\'entreprise.'],
        ['Hébergement', 'L\'endroit où le site et ses données sont stockés.'],
        ['Traceur (cookie)', 'Petit fichier déposé sur l\'appareil du visiteur ; certains exigent son accord préalable.'],
        ['Mentions légales', 'Les informations obligatoires sur l\'éditeur et l\'hébergeur du site.'],
        ['Texte alternatif', 'La description d\'une image, lue par les lecteurs d\'écran.'],
        ['Réversibilité', 'La possibilité de récupérer son site et ses contenus pour changer d\'outil.'],
    ],
    'objectifs': [
        ['O1', 'Formuler', 'Formuler à l\'oral un cahier des charges exploitable : objectif, pages, contenus, action attendue du visiteur.', 'Cahier des charges dicté et arborescence validés par un tiers.'],
        ['O2', 'Piloter', 'Piloter à la voix un outil de génération et corriger le résultat par itérations successives.', 'Trois corrections réussies avec les quatre leviers.'],
        ['O3', 'Produire et vérifier', 'Produire les contenus (textes, titres, tarifs, coordonnées) en contrôlant chaque information.', 'Aucune information inventée restante sur le site.'],
        ['O4', 'Publier conforme', 'Mettre en ligne un site conforme : mentions légales, confidentialité, traceurs, accessibilité.', 'Checklist de conformité complète sur le site publié.'],
        ['O5', 'Maintenir', 'Faire évoluer le site seul, sans dépendre d\'un prestataire.', 'Modification réalisée seul en séance + fiche « faire évoluer mon site ».'],
    ],
    'jours_detail': [
        {
            'titre': None,
            'fil': 'passer d\'une activité décrite à voix haute à un site publié, conforme et que l\'on sait tenir seul.',
            'lignes': [
                ('08:00-08:30', '30 min', 'Séquence 0 « Quinze secondes »', 'Deux sites projetés 15 secondes : que vend l\'entreprise, où, comment la joindre ? Attentes ; information RGPD et transparence IA (art. 50).', 'Projection + vote à main levée.', 'Diaporama.'),
                ('08:30-09:15', '45 min', 'Les quatre phrases (O1)', 'Qui êtes-vous, que proposez-vous, pour qui, que doit faire le visiteur ; dictée de 90 secondes, le voisin reformule.', 'Atelier en binômes.', 'Micro-casque, fiche « 4 phrases ».'),
                ('09:15-10:00', '45 min', 'L\'arborescence (O1)', '3 à 5 pages, une action attendue par page, pages obligatoires.', 'Atelier au paperboard.', 'Paperboard, gabarit d\'arborescence.'),
                PAUSE_MATIN,
                ('10:15-10:45', '30 min', 'Choisir son outil', 'Coût réel la deuxième année, hébergement des données, propriété du nom de domaine, réversibilité.', 'Comparaison guidée.', 'Grille de choix.'),
                ('10:45-11:20', '35 min', 'Première génération (O2)', 'L\'anatomie d\'une consigne dictée ; générer le site à partir du cahier des charges.', 'Démonstration puis pratique.', 'Générateur de site.'),
                ('11:20-12:00', '40 min', 'Corriger et « chasse aux inventions » (O2, O3)', 'Les 4 leviers : compléter le contexte, montrer un exemple, réduire la demande, demander ce qui manque ; surligner ce que l\'outil a inventé.', 'Atelier individuel accompagné.', 'Surligneur numérique, fiche leviers.'),
                DEJEUNER,
                ('13:00-14:15', '75 min', 'Produire page par page (O3)', 'Textes utiles, titres qui disent quelque chose, images légales et légères, texte alternatif dicté avec l\'image.', 'Production individuelle, correction individualisée.', 'Photos du stagiaire, banque d\'images libres.'),
                ('14:15-15:00', '45 min', 'La page contact (O3, O4)', 'Formulaire minimal (RGPD art. 5.1.c), information sous le formulaire (art. 13), case newsletter jamais pré-cochée.', 'Démonstration + application.', 'Modèle de mention d\'information.'),
                PAUSE_APREM,
                ('15:15-16:00', '45 min', 'Publier en conformité (O4)', 'Mentions légales, politique de confidentialité, traceurs ; accessibilité : contrastes, titres, liens explicites, clavier ; mise en ligne et sauvegarde.', 'Checklist guidée.', 'Checklist de conformité.'),
                ('16:00-16:45', '45 min', 'Évaluation finale (O5)', 'Le site publié évalué sur la grille remise le matin ; une modification réalisée seul ; quiz de 10 questions.', 'Mise en situation + quiz.', 'Grille critériée, quiz.'),
                ('16:45-17:00', '15 min', 'Plan d\'action à 30 jours', 'Fiche « faire évoluer mon site » ; satisfaction à chaud.', 'Engagement individuel.', 'Fiche d\'action.'),
            ],
            'livrables': ['cahier des charges dicté', 'arborescence validée', 'site publié et conforme', 'fiche « faire évoluer mon site »'],
        },
    ],
    'moyens': MOYENS_BASE + [
        'Un ordinateur portable par participant ; micro-casques fournis ; espace calme pour la dictée.',
        'Accès à un générateur de site de démonstration, et nom de domaine de test si le stagiaire n\'a pas le sien.',
        'Banque d\'images libres de droits et cas de secours fictif (une pâtisserie de Saint-Leu).',
    ],
    'grille': [
        ['1. Cahier des charges', 'Absent', 'Partiel', 'Les 4 phrases + action attendue', 'Arbitrages explicités'],
        ['2. Arborescence', 'Pages sans logique', 'Pages sans action', '3 à 5 pages, une action chacune', 'Parcours visiteur justifié'],
        ['3. Pilotage', 'Aucune correction', 'Corrections au hasard', 'Leviers utilisés à bon escient', 'Consignes réutilisables'],
        ['4. Exactitude', 'Inventions publiées', 'Vérification partielle', 'Toutes les informations vérifiées', 'Sources conservées'],
        ['5. Contenus', 'Illisibles', 'Génériques', 'Titres et textes utiles', 'Voix de l\'entreprise reconnaissable'],
        ['6. Conformité', 'Mentions absentes', 'Incomplètes', 'Mentions, confidentialité, traceurs', 'Justification selon l\'activité'],
        ['7. Accessibilité', 'Non contrôlée', 'Partielle', 'Contrastes, titres, alternatives, clavier', 'Corrections testées'],
        ['8. Autonomie', 'Dépend d\'un tiers', 'Modification guidée', 'Modification seul', 'Explique à un pair comment faire'],
    ],
    'seuil': '16/24 minimum, avec au moins 2/3 sur les critères 4 et 6. Un beau site qui affiche un faux tarif ou aucune mention légale n\'est pas publiable.',
    'seuil_points': '16/24', 'critiques': '4 et 6',
    'suivi': suivi_standard(1, 'Chasse aux inventions + correction individualisée', 'site publié'),
    'quiz': [
        ('Quelle question vient en premier pour un site utile ?', ['A. Quelle couleur ?', 'B. Que doit faire le visiteur maintenant ?', 'C. Combien de pages ?', 'D. Quel outil ?'], 'B', 'L\'action attendue organise tout le site.'),
        ('Le générateur affiche « Label Qualité 2026 » que vous n\'avez pas. Que faire ?', ['A. Le garder', 'B. Le supprimer avant publication', 'C. Le mettre en petit', 'D. L\'ajouter à toutes les pages'], 'B', 'Une allégation fausse est une pratique commerciale trompeuse (C. conso. L.121-2).'),
        ('Que faut-il vérifier avant de choisir un outil de site ?', ['A. Le nombre de modèles', 'B. Coût la 2e année, hébergement, propriété du nom de domaine, réversibilité', 'C. La couleur du logo', 'D. Rien'], 'B', 'Ce sont les critères qui évitent la dépendance.'),
        ('Un formulaire de contact doit demander…', ['A. le maximum d\'informations', 'B. le strict nécessaire pour répondre', 'C. la date de naissance', 'D. un justificatif'], 'B', 'Minimisation (RGPD art. 5.1.c).'),
        ('Vrai ou faux : la case d\'inscription à la lettre d\'information peut être pré-cochée.', ['Vrai', 'Faux'], 'Faux', 'Le consentement suppose un acte positif.'),
        ('Les mentions légales doivent indiquer notamment…', ['A. l\'éditeur et l\'hébergeur', 'B. le chiffre d\'affaires', 'C. les salaires', 'D. le mot de passe'], 'A', 'Obligation de la loi pour la confiance dans l\'économie numérique.'),
        ('Un traceur publicitaire peut être déposé…', ['A. sans rien demander', 'B. après accord du visiteur', 'C. seulement le week-end', 'D. si le site est petit'], 'B', 'Les traceurs non essentiels exigent un consentement préalable.'),
        ('À quoi sert le texte alternatif d\'une image ?', ['A. Au référencement uniquement', 'B. À décrire l\'image pour les lecteurs d\'écran', 'C. À la compresser', 'D. À rien'], 'B', 'C\'est un geste d\'accessibilité de base.'),
        ('Quel levier utiliser quand le résultat est trop général ?', ['A. Recommencer de zéro', 'B. Compléter le contexte', 'C. Changer d\'outil', 'D. Abandonner'], 'B', 'Le manque de contexte est la première cause d\'un résultat générique.'),
        ('Le nom de domaine doit être enregistré…', ['A. au nom du prestataire', 'B. au nom de l\'entreprise', 'C. peu importe', 'D. au nom de l\'outil'], 'B', 'Sinon l\'entreprise ne maîtrise pas son adresse.'),
    ],
    'validation': [
        ['Formuler le cahier des charges', 'Cahier dicté + arborescence', 'Revue par un tiers', 'Score ≥ 2 aux critères 1 et 2'],
        ['Piloter l\'outil', 'Historique de corrections', 'Observation', 'Score ≥ 2 au critère 3'],
        ['Produire des contenus exacts', 'Site sans invention', 'Contrôle sur grille', 'Score ≥ 2 aux critères 4 et 5'],
        ['Publier conforme', 'Checklist sur site publié', 'Contrôle sur grille', 'Score ≥ 2 aux critères 6 et 7'],
        ['Maintenir seul', 'Modification réalisée seul', 'Mise en situation', 'Score ≥ 2 au critère 8'],
    ],
    'defi': {
        'intro': 'Vous publiez le site de votre activité réelle, ou celui du cas de secours.',
        'etapes': [
            'Dicter les quatre phrases et montrer l\'arborescence validée.',
            'Générer le site, puis montrer deux corrections et l\'invention la plus grave que vous avez supprimée.',
            'Publier avec mentions légales, politique de confidentialité et gestion des traceurs.',
            'Réaliser seul une modification demandée par le formateur (ajouter un tarif, changer un horaire).',
            'Présenter votre site en 3 minutes : visiteur visé, action attendue, prochaine évolution.',
        ],
    },
    'annexes': [
        {'titre': 'Les quatre phrases d\'un site utile', 'tableau': (['Question', 'Votre réponse (90 secondes à l\'oral)'], [
            ['Qui êtes-vous ?', 'Nom, métier, lieu, depuis quand.'], ['Que proposez-vous ?', 'Vos 3 offres principales, avec leur prix si vous l\'affichez.'],
            ['Pour qui ?', 'Le client type et son besoin.'], ['Que doit faire le visiteur ?', 'Une seule action : appeler, réserver, demander un devis.'],
        ], [1, 3])},
        {'titre': 'Checklist de conformité avant publication', 'puces': [
            'Mentions légales : éditeur, statut, SIRET, directeur de publication, hébergeur.',
            'Politique de confidentialité : données collectées, finalités, durée, droits, contact.',
            'Traceurs non essentiels déposés seulement après accord ; refus aussi simple qu\'accepter.',
            'Formulaire minimal, mention d\'information sous le formulaire, aucune case pré-cochée.',
            'Aucune information inventée : tarifs, horaires, labels, avis vérifiés.',
            'Contrastes suffisants, titres hiérarchisés, liens explicites, textes alternatifs, navigation au clavier.',
            'Nom de domaine au nom de l\'entreprise ; sauvegarde réalisée.',
        ]},
    ],
    'accessibilite': 'Point de vigilance : le pilotage à la voix peut être un obstacle (trouble de la parole, bégaiement, surdité, gêne à parler en groupe). Aménagements prévus : dictée depuis un espace à l\'écart, casque à réduction de bruit, saisie au clavier acceptée en substitution intégrale de la dictée — la compétence évaluée est la structuration de la demande, pas la production sonore —, temps allongé pour corriger les erreurs de transcription.',
    'sources': [
        'CNIL, « Cookies et autres traceurs » — https://www.cnil.fr/fr/cookies-et-autres-traceurs',
        'Loi n° 2004-575 pour la confiance dans l\'économie numérique, article 6 — https://www.legifrance.gouv.fr/',
        'Règlement (UE) 2024/1689 (IA Act), article 50 — https://eur-lex.europa.eu/',
    ],
}
