from commun import DEJEUNER, MOYENS_BASE, PAUSE_APREM, PAUSE_MATIN, VERSION, suivi_standard

F = {
    'ref': 'FOR-0002', 'fichier': 'programme-detaille-for-0002-automatisation-sans-code-n8n.pdf', 'nom_affiche': 'Programme detaille - FOR-0002 - Automatisation sans code (n8n).pdf',
    'titre': 'Automatisation sans code : Relier ses outils et supprimer les tâches répétitives (n8n)',
    'nom': 'Automatisation sans code',
    'promesse_titre': 'Relier ses outils et supprimer les tâches répétitives, avec n8n',
    'promesse': "À l'issue des deux journées, chaque participant repart avec une automatisation qui tourne sur une tâche réelle de son activité, documentée pour un collègue, et une fiche de gain chiffrée présentable à sa direction ou à un financeur.",
    'format_court': 'Présentiel - 2 jours', 'jours': 2, 'heures': 16, 'validation_courte': '1 automatisation en service',
    'inter': '990', 'intra': '2 900', 'version': VERSION,
    'public_court': 'dirigeants de TPE-PME, indépendants, fonctions administratives et commerciales.',
    'public': 'Dirigeants de TPE-PME, indépendants et fonctions administratives ou commerciales qui veulent gagner du temps et fiabiliser leurs processus (devis, relances, ressaisies, inscriptions, notifications).',
    'prerequis': 'Utilisation courante des outils bureautiques et du web. Aucune compétence en programmation. Venir avec une tâche répétitive réelle de son activité.',
    'materiel': 'Un ordinateur portable par stagiaire (inter : apporter le sien), navigateur à jour. Les comptes de démonstration n8n sont fournis.',
    'production': 'Une automatisation en service (déclencheur → conditions → actions), testée sur des cas limites, documentée, et sa fiche de gain chiffrée.',
    'outils': 'n8n (instance de formation fournie ; auto-hébergement possible en Europe), tableur ou base de données en ligne, messagerie de test, formulaire en ligne.',
    'financements': 'OPCO, plan de développement des compétences, France Travail (AIF), Région Réunion',
    'positionnement': {
        'idee': "Apprendre à automatiser, c'est d'abord apprendre à regarder son travail. On chiffre une tâche, on la dessine au crayon, puis seulement on la construit. L'outil n8n est le terrain d'entraînement : la méthode reste valable avec n'importe quel outil.",
        'intro': 'Le module est construit pour des personnes qui n\'ont jamais programmé :',
        'points': [
            'Partir d\'une tâche réelle, fréquente et à règles stables, et la chiffrer en minutes par mois.',
            'Dessiner le schéma « Quand / Si / Alors » avant d\'ouvrir l\'outil.',
            'Construire pas à pas : un déclencheur, une condition, une action, puis tester.',
            'Tester comme si cela devait casser : données manquantes, doublons, erreur d\'envoi.',
            'Sécuriser les données et mesurer le gain réel, preuve à l\'appui.',
        ],
        'vigilance': "Une automatisation mal conçue reproduit une erreur des centaines de fois, sans que personne ne la voie. C'est pourquoi chaque workflow construit en séance comporte une alerte en cas d'échec et un responsable nommé.",
    },
    'vocabulaire': [
        ['Automatisation', 'Une tâche que l\'ordinateur exécute seul, à chaque fois qu\'un événement se produit, selon des règles écrites à l\'avance.'],
        ['Workflow', 'L\'enchaînement des étapes d\'une automatisation, du point de départ à la dernière action.'],
        ['Déclencheur', 'L\'événement qui lance l\'automatisation : un formulaire reçu, un courriel, une heure précise.'],
        ['Condition', 'Le « si » : la règle qui oriente la suite (si le montant dépasse 1 000 €, alors…).'],
        ['Action', 'Ce que fait l\'automatisation : écrire dans un tableau, envoyer un courriel, créer un document.'],
        ['Nœud', 'Une case du schéma dans n8n : chaque nœud fait une seule chose.'],
        ['Exécution', 'Un passage complet du workflow ; n8n garde l\'historique de chaque exécution.'],
        ['Identifiants', 'Les accès que l\'automatisation utilise pour se connecter à un outil ; ils se protègent comme un mot de passe.'],
    ],
    'objectifs': [
        ['O1', 'Identifier', 'Repérer dans son activité les tâches répétitives automatisables selon quatre critères : fréquence, règles stables, volume, coût de l\'erreur.', 'Carte du processus cible chiffrée en minutes par mois.'],
        ['O2', 'Concevoir', 'Dessiner un workflow simple : déclencheur → conditions → actions, avec les données qui circulent.', 'Schéma « Quand / Si / Alors » validé par un binôme.'],
        ['O3', 'Construire', 'Mettre en place une automatisation sans code (formulaire → base de données → courriel).', 'Workflow exécuté trois fois sans erreur sur des données de test.'],
        ['O4', 'Sécuriser', 'Protéger les identifiants et les données traitées ; appliquer la minimisation et inscrire le traitement au registre (RGPD).', 'Fiche « données et accès » complétée ; aucune donnée inutile collectée.'],
        ['O5', 'Mesurer et fiabiliser', 'Tester les cas limites, prévoir une alerte en cas d\'échec et chiffrer le gain réel en temps et en fiabilité.', 'Fiche de gain chiffrée ; alerte d\'échec fonctionnelle.'],
    ],
    'jours_detail': [
        {
            'titre': 'Diagnostiquer et concevoir',
            'fil': 'passer d\'une tâche qui agace à un schéma d\'automatisation chiffré et validé.',
            'lignes': [
                ('08:00-08:45', '45 min', 'Séquence 0 « La chaîne humaine »', 'Jouer à la main un processus de devis, chronomètre en main ; recueillir les attentes ; information RGPD et transparence IA.', 'Jeu de rôle collectif, tour de table.', 'Cartes de rôle, chronomètre, paperboard.'),
                ('08:45-10:00', '75 min', 'Ce qui mérite d\'être automatisé (O1)', 'Les quatre critères ; cartographier son processus réel et le chiffrer en minutes par mois.', 'Apport court + atelier individuel.', 'Fiche « carte du processus ».'),
                PAUSE_MATIN,
                ('10:15-11:00', '45 min', 'La grammaire d\'un workflow (O2)', 'Déclencheur, conditions, actions, données qui circulent ; lire un workflow existant.', 'Démonstration commentée.', 'Instance n8n de formation.'),
                ('11:00-12:00', '60 min', 'Dessiner avant de construire (O2)', 'Schéma « Quand / Si / Alors » au crayon, validé en binôme sur trois questions.', 'Atelier en binômes + revue par les pairs.', 'Gabarit de schéma, feutres.'),
                DEJEUNER,
                ('13:00-13:45', '45 min', 'Choisir son outil', 'Hébergement des données, coût réel la deuxième année, réversibilité, auto-hébergement possible avec n8n.', 'Comparaison guidée.', 'Grille de choix des outils.'),
                ('13:45-15:00', '75 min', 'Première construction guidée (O3)', 'Formulaire → tableur ou base → courriel de confirmation ; nœuds, connexions, exécutions, historique.', 'Démonstration « je montre, nous faisons, vous faites ».', 'n8n, formulaire et messagerie de test.'),
                PAUSE_APREM,
                ('15:15-16:30', '75 min', 'Construire son propre workflow (O3)', 'Chaque stagiaire construit le workflow de son schéma ; accompagnement individualisé.', 'Pratique individuelle accompagnée.', 'n8n, schéma validé du matin.'),
                ('16:30-17:00', '30 min', 'Point d\'étape', 'Ce qui fonctionne, ce qui bloque ; consigne pour la journée 2 ; quiz flash.', 'Tour de table + quiz oral.', 'Mur des pannes (paperboard).'),
            ],
            'livrables': ['carte du processus chiffrée', 'schéma « Quand / Si / Alors » validé', 'premier workflow exécuté'],
        },
        {
            'titre': 'Fiabiliser, sécuriser, mesurer',
            'fil': 'transformer un workflow qui marche une fois en un outil fiable, sûr et dont le gain est prouvé.',
            'lignes': [
                ('08:00-08:30', '30 min', 'Réactivation', 'Quiz de reprise ; « le mur des pannes » de la veille, résolu en groupe.', 'Quiz oral + résolution collective.', 'Paperboard, diaporama.'),
                ('08:30-10:00', '90 min', 'Conditions, boucles et données (O3)', 'Conditions multiples, boucles, transformation de données, valeurs manquantes.', 'Démonstration + atelier sur son workflow.', 'n8n, jeux de données fictifs.'),
                PAUSE_MATIN,
                ('10:15-11:15', '60 min', 'Tester comme si ça devait casser (O5)', 'Cas limites, doublons, données absentes ; alerte en cas d\'échec.', 'Atelier « casse-moi ça » en binômes croisés.', 'Fiche de tests, messagerie de test.'),
                ('11:15-12:00', '45 min', 'Documenter pour un collègue (O5)', 'Le workflow doit pouvoir être repris par quelqu\'un qui ne l\'a pas construit.', 'Rédaction guidée + test du collègue.', 'Gabarit de documentation.'),
                DEJEUNER,
                ('13:00-14:00', '60 min', 'Sécuriser les données (O4)', 'Où sont mes données, qui y accède, combien de temps ; identifiants ; sous-traitants (RGPD art. 28) ; registre (art. 30).', 'Étude de cas + fiche à compléter.', 'Fiche « données et accès », extrait de registre.'),
                ('14:00-15:00', '60 min', 'Mesurer le gain réel (O5)', 'Temps avant / après, taux d\'erreur, coût de l\'outil ; la fiche de gain.', 'Calcul guidé sur ses chiffres.', 'Fiche de gain.'),
                PAUSE_APREM,
                ('15:15-16:15', '60 min', 'Évaluation finale', 'Défi final : présenter son workflow en service ; quiz de 10 questions.', 'Mise en situation notée sur grille.', 'Grille critériée, quiz.'),
                ('16:15-17:00', '45 min', 'Plan d\'ancrage', 'Rejeu de « la chaîne humaine » : temps avant / après ; les deux prochaines automatisations ; satisfaction.', 'Engagement individuel écrit.', 'Fiche plan d\'action, questionnaire.'),
            ],
            'livrables': ['workflow fiabilisé et documenté', 'fiche « données et accès »', 'fiche de gain chiffrée'],
        },
    ],
    'moyens': MOYENS_BASE + [
        'Un ordinateur portable par participant avec navigateur à jour.',
        'Une instance n8n de formation par participant (ou un espace partagé) et des jeux de données fictifs, sans données clients réelles.',
        'Une adresse de messagerie de test par participant.',
    ],
    'grille': [
        ['1. Choix de la tâche', 'Tâche floue ou rare', 'Tâche fréquente non chiffrée', 'Tâche chiffrée selon les 4 critères', 'Arbitrage entre plusieurs tâches justifié'],
        ['2. Schéma', 'Aucun schéma', 'Étapes sans règles', 'Quand / Si / Alors complet', 'Données et exceptions anticipées'],
        ['3. Construction', 'Workflow non fonctionnel', 'Fonctionne une fois', 'Trois exécutions sans erreur', 'Structure claire et réutilisable'],
        ['4. Conditions et données', 'Absentes', 'Une condition simple', 'Conditions et transformations correctes', 'Cas multiples gérés proprement'],
        ['5. Tests et alerte', 'Aucun test', 'Test du cas nominal', 'Cas limites testés + alerte', 'Anomalies priorisées et corrigées'],
        ['6. Sécurité et RGPD', 'Risque majeur (données inutiles, accès ouverts)', 'Mesures partielles', 'Minimisation, accès et registre traités', 'Justification selon le contexte'],
        ['7. Documentation', 'Absente', 'Notes personnelles', 'Reprenable par un collègue', 'Testée par un collègue'],
        ['8. Mesure du gain', 'Non chiffrée', 'Estimation vague', 'Fiche de gain chiffrée', 'Gain et coût comparés sur 12 mois'],
    ],
    'seuil': '16/24 minimum, avec au moins 2/3 sur les critères 3, 5 et 6. Un workflow rapide ne compense pas une faille de sécurité ou l\'absence d\'alerte.',
    'seuil_points': '16/24', 'critiques': '3, 5 et 6',
    'suivi': suivi_standard(2, 'Schéma validé en binôme, exécutions du workflow', 'workflow en service'),
    'quiz': [
        ('Quel critère rend une tâche peu adaptée à l\'automatisation ?', ['A. Elle revient chaque jour', 'B. Ses règles changent à chaque fois', 'C. Elle concerne beaucoup de dossiers', 'D. Une erreur coûte cher'], 'B', 'Sans règles stables, l\'automatisation reproduit des décisions qu\'elle ne peut pas prendre.'),
        ('Dans un workflow, le déclencheur est…', ['A. la dernière action', 'B. l\'événement qui lance l\'automatisation', 'C. la base de données', 'D. le message d\'erreur'], 'B', 'Tout workflow commence par un événement : formulaire, courriel, horaire.'),
        ('Vrai ou faux : il faut construire dans l\'outil avant de dessiner le schéma.', ['Vrai', 'Faux'], 'Faux', 'Le schéma « Quand / Si / Alors » évite de construire le mauvais processus.'),
        ('Que faut-il prévoir pour savoir qu\'une automatisation a échoué ?', ['A. Rien, elle s\'arrête', 'B. Une alerte envoyée à un responsable', 'C. Un second outil', 'D. Une relance manuelle chaque matin'], 'B', 'Une erreur silencieuse se répète : l\'alerte rend l\'échec visible.'),
        ('Où conserver les identifiants de connexion utilisés par n8n ?', ['A. Dans le nom du nœud', 'B. Dans le gestionnaire d\'identifiants de l\'outil, avec des droits limités', 'C. Dans un courriel', 'D. Dans la documentation partagée'], 'B', 'Les identifiants se protègent comme un mot de passe et ne s\'écrivent jamais en clair.'),
        ('Un formulaire de contact collecte la date de naissance « au cas où ». Quel principe du RGPD est méconnu ?', ['A. La minimisation', 'B. La portabilité', 'C. Le droit à l\'oubli', 'D. La certification'], 'A', 'On ne collecte que les données nécessaires à la finalité (RGPD art. 5.1.c).'),
        ('L\'éditeur de l\'outil d\'automatisation traite vos données pour votre compte. Il est…', ['A. responsable de traitement', 'B. sous-traitant, avec un contrat (art. 28)', 'C. sans obligation', 'D. un simple fournisseur de matériel'], 'B', 'Le contrat de sous-traitance est obligatoire et se vérifie avant de choisir l\'outil.'),
        ('Quel test est le plus utile avant la mise en service ?', ['A. Le cas qui marche', 'B. Les cas limites : donnée absente, doublon, erreur d\'envoi', 'C. Une démonstration au client', 'D. Le changement de couleur des nœuds'], 'B', 'Ce sont les cas limites qui cassent en production.'),
        ('Comment prouver le gain d\'une automatisation ?', ['A. Par une impression générale', 'B. Temps avant / après, erreurs évitées et coût de l\'outil, chiffrés', 'C. Par le nombre de nœuds', 'D. Par la vitesse du serveur'], 'B', 'La fiche de gain compare des chiffres, pas des impressions.'),
        ('Pourquoi documenter son workflow ?', ['A. Pour l\'audit uniquement', 'B. Pour qu\'un collègue puisse le reprendre et l\'arrêter', 'C. Ce n\'est pas utile', 'D. Pour l\'éditeur'], 'B', 'Un workflow que seul son auteur comprend devient un risque dès son absence.'),
    ],
    'validation': [
        ['Diagnostiquer une tâche', 'Carte du processus chiffrée', 'Dépôt', 'Score ≥ 2 au critère 1'],
        ['Concevoir le workflow', 'Schéma « Quand / Si / Alors »', 'Revue par les pairs', 'Score ≥ 2 au critère 2'],
        ['Construire et fiabiliser', 'Workflow en service + tests', 'Démonstration en direct', 'Score ≥ 2 aux critères 3 à 5'],
        ['Sécuriser les données', 'Fiche « données et accès »', 'Dépôt + questions', 'Score ≥ 2 au critère 6'],
        ['Mesurer le gain', 'Fiche de gain', 'Présentation', 'Score ≥ 2 au critère 8'],
    ],
    'defi': {
        'intro': 'Vous devez mettre en service l\'automatisation d\'une tâche réelle de votre activité, ou du cas de secours proposé par le formateur (prise de rendez-vous d\'un garage de Saint-Pierre).',
        'etapes': [
            'Présenter la tâche choisie et son coût actuel en minutes par mois.',
            'Montrer le schéma « Quand / Si / Alors » validé par votre binôme.',
            'Exécuter le workflow devant le groupe, puis provoquer un cas limite et montrer l\'alerte.',
            'Présenter la fiche « données et accès » : quelles données, où, qui y accède, combien de temps.',
            'Présenter la fiche de gain et votre prochaine automatisation, en 4 minutes au total.',
        ],
    },
    'annexes': [
        {'titre': 'Fiche « carte du processus »', 'tableau': (['Champ', 'Question à renseigner'], [
            ['1. Tâche', 'Que faites-vous exactement, étape par étape ?'], ['2. Fréquence', 'Combien de fois par semaine ou par mois ?'],
            ['3. Durée', 'Combien de minutes à chaque fois ?'], ['4. Règles', 'Les décisions suivent-elles toujours les mêmes règles ? Lesquelles ?'],
            ['5. Outils', 'Quels logiciels ou fichiers sont utilisés ?'], ['6. Données', 'Quelles données personnelles circulent ? Sont-elles toutes nécessaires ?'],
            ['7. Coût de l\'erreur', 'Que se passe-t-il si une étape est oubliée ou fausse ?'],
        ], [1, 3])},
        {'titre': 'Checklist avant mise en service', 'puces': [
            'Le déclencheur, les conditions et les actions correspondent au schéma validé.',
            'Le workflow a tourné trois fois sans erreur sur des données de test.',
            'Les cas limites (donnée absente, doublon, erreur d\'envoi) ont été testés.',
            'Une alerte prévient un responsable nommé en cas d\'échec.',
            'Les identifiants sont stockés dans le gestionnaire de l\'outil, avec des droits limités.',
            'Seules les données nécessaires sont collectées ; le traitement figure au registre.',
            'Le contrat de sous-traitance de l\'outil a été vérifié (RGPD art. 28).',
            'La documentation permet à un collègue de reprendre et d\'arrêter le workflow.',
        ]},
    ],
    'accessibilite': 'Formation accessible aux personnes en situation de handicap ; aucun justificatif médical n\'est demandé. Déjà intégré : séquences de 80 minutes maximum, consignes à l\'oral et à l\'écrit, livrables écrits. Sur demande : support en corps 16 points ou lisible par lecteur d\'écran, temps majoré d\'un tiers aux évaluations, travail en binôme pour la construction (l\'apprentissage porte sur la conception, non sur la manipulation), atelier « schéma au crayon » sur support numérique agrandi.',
    'sources': [
        'n8n, documentation officielle — https://docs.n8n.io/',
        'CNIL, « Les bases légales » et « Le registre des activités de traitement » — https://www.cnil.fr/',
        'Règlement (UE) 2016/679 (RGPD), articles 5, 28, 30 et 32 — https://eur-lex.europa.eu/',
    ],
}
