from commun import DEJEUNER, MOYENS_BASE, PAUSE_APREM, PAUSE_MATIN, VERSION, suivi_standard

F = {
    'ref': 'FOR-0015', 'fichier': 'programme-detaille-for-0015-ia-souveraine.pdf', 'nom_affiche': 'Programme detaille - FOR-0015 - IA souveraine.pdf',
    'titre': "IA souveraine : Faire tourner l'IA sur ses propres machines, sans donnée sortante",
    'nom': 'IA souveraine',
    'promesse_titre': "Faire tourner l'IA sur ses propres machines, sans donnée sortante",
    'promesse': "En deux jours, chaque participant installe un modèle d'IA sur son poste, prouve réseau coupé qu'aucune donnée ne sort, le branche sur un fonds documentaire maîtrisé, chiffre le coût sur 36 mois et repart avec la note d'arbitrage « local ou distant » pour sa direction.",
    'format_court': 'Présentiel - 2 jours', 'jours': 2, 'heures': 16, 'validation_courte': '1 note d\'arbitrage soutenue',
    'inter': '890', 'intra': '2 700', 'version': VERSION,
    'public_court': 'dirigeants, responsables informatiques et référents IA de structures traitant des données sensibles.',
    'public': 'Dirigeants, responsables informatiques, référents IA et prestataires informatiques de TPE-PME qui traitent des données sensibles ou couvertes par le secret : cabinets comptables et juridiques, santé, RH, bureaux d\'études, collectivités ; structures qui doivent travailler hors connexion.',
    'prerequis': 'Usage courant de l\'IA générative (niveau « IA générative au travail » acquis). Aucune programmation, mais accepter de travailler dans un terminal. Poste avec droits d\'administration, 16 Go de mémoire vive recommandés (8 Go minimum), 20 Go de disque libre. Les modèles sont téléchargés par le formateur avant la session.',
    'materiel': 'Ordinateur portable avec droits d\'administration, 16 Go de mémoire vive recommandés (8 Go minimum), 20 Go d\'espace disque libre.',
    'production': 'Un modèle local installé et prouvé « sans donnée sortante », un comparatif de deux tailles de modèle, une recherche documentaire locale contrôlée, un coût complet sur 36 mois, une entrée de registre et une note d\'arbitrage d\'une page.',
    'outils': 'Ollama (moteur d\'exécution locale), modèles ouverts téléchargés en amont, interface locale, terminal, tableur.',
    'financements': 'OPCO, plan de développement des compétences',
    'positionnement': {
        'idee': "Le local n'est ni magique ni hors RGPD : on dit ce que l'on gagne et ce que l'on perd avant d'installer, on prouve ce qui est affirmé, et l'on chiffre honnêtement.",
        'intro': 'Le module avance comme un audit que l\'on mène soi-même :',
        'points': [
            'Où part la donnée : appel distant, hébergement européen, exécution locale.',
            'Installer, puis prouver réseau coupé qu\'aucune donnée ne sort.',
            'Choisir la taille de modèle que la machine peut réellement porter.',
            'Brancher un fonds documentaire en maîtrisant l\'étendue des droits.',
            'Chiffrer sur 36 mois, inscrire au registre et arbitrer par écrit.',
        ],
        'vigilance': "Le moteur peut être local alors que l'interface posée par-dessus ne l'est pas. La preuve « réseau coupé » est faite sur l'ensemble de la chaîne, pas seulement sur le moteur.",
    },
    'vocabulaire': [
        ['Modèle local', 'Un modèle d\'IA exécuté sur la machine de l\'entreprise, sans appel à un serveur extérieur.'],
        ['Appel distant', 'La demande part sur les serveurs d\'un éditeur, qui renvoie la réponse.'],
        ['Moteur d\'exécution', 'Le logiciel qui fait tourner le modèle sur le poste (ici Ollama).'],
        ['Paramètres', 'La taille d\'un modèle ; plus grand n\'est pas toujours meilleur pour votre machine.'],
        ['Mémoire vive', 'La mémoire de travail de l\'ordinateur ; elle limite la taille du modèle utilisable.'],
        ['Fonds documentaire', 'L\'ensemble de documents que l\'on autorise le modèle à consulter.'],
        ['Registre', 'Le document RGPD qui liste les traitements de données de l\'entreprise (art. 30).'],
        ['Réversibilité', 'La capacité à changer de solution sans perdre ses données ni son travail.'],
    ],
    'objectifs': [
        ['O1', 'Comprendre', 'Distinguer modèle local et appel distant, et ce que chacun expose réellement comme données.', 'Atelier « Où part la donnée ? » : 8 situations sur 10.'],
        ['O2', 'Appliquer', 'Installer un moteur local et faire répondre un modèle sur son poste.', 'Première réponse obtenue en autonomie en moins de 30 minutes.'],
        ['O3', 'Analyser', 'Démontrer, réseau coupé, qu\'aucune donnée saisie ne quitte la machine.', 'Démonstration conduite et commentée sans aide.'],
        ['O4', 'Évaluer', 'Choisir la taille de modèle que le matériel peut porter.', 'Deux modèles chronométrés, choix justifié par écrit.'],
        ['O5', 'Appliquer', 'Brancher le modèle sur un fonds documentaire et contrôler l\'étendue des droits.', 'Réponse exacte à une question dont la réponse n\'existe que dans les documents fournis.'],
        ['O6', 'Évaluer', 'Chiffrer le coût complet sur 36 mois face à un abonnement.', 'Tableau à deux colonnes avec chiffres réels et conclusion datée.'],
        ['O7', 'Appliquer', 'Inscrire le traitement local au registre des activités de traitement.', 'Entrée de registre complète (finalité, données, durée, destinataires, sécurité).'],
        ['O8', 'Créer', 'Rédiger la note d\'arbitrage « local ou distant » pour sa direction.', 'Note d\'une page, recommandation tranchée et conditions.'],
    ],
    'jours_detail': [
        {
            'titre': 'Installer et prouver',
            'fil': 'passer d\'une promesse (« vos données ne sortent pas ») à une preuve faite de ses propres mains.',
            'lignes': [
                ('08:00-08:45', '45 min', 'Séquence 0 : trois outils, trois trajets', 'La même question posée à trois outils : où part la donnée ? Attentes ; information RGPD.', 'Démonstration + débat.', 'Schéma des flux.'),
                ('08:45-10:00', '75 min', 'Où part la donnée ? (O1)', 'Appel distant, hébergement européen, exécution locale ; ce que l\'on gagne et perd en local ; 10 situations à classer.', 'Atelier en binômes.', 'Cartes « situations ».'),
                PAUSE_MATIN,
                ('10:15-12:00', '105 min', 'Installation du modèle local (O2)', 'Installer Ollama, vérifier la version, télécharger, lancer et lister un modèle ; poids sur le disque ; ne jamais télécharger le jour J.', 'Pas à pas écran par écran.', 'Terminal, modèles pré-téléchargés.'),
                DEJEUNER,
                ('13:00-13:15', '15 min', 'Réveil pédagogique', 'Trois questions de reprise à main levée, sans note.', 'Oral collectif.', '-'),
                ('13:15-15:00', '105 min', 'La preuve par le câble (O3)', 'Vérifier l\'écoute en local (port 11434), couper le réseau, saisir une donnée fictive sensible, rétablir et contrôler l\'absence de transmission différée ; le piège de l\'interface.', 'Démonstration puis réalisation par chacun.', 'Moniteur réseau, données fictives.'),
                PAUSE_APREM,
                ('15:15-17:00', '105 min', 'La machine peut-elle suivre ? (O4)', 'Relever mémoire et carte graphique ; deux tailles de modèle, même demande métier, deux chronomètres ; au-delà de 10 s, l\'utilisateur abandonne.', 'Mesure comparée + justification écrite.', 'Chronomètre, fiche comparative.'),
            ],
            'livrables': ['modèle local installé', 'preuve « réseau coupé » commentée', 'comparatif de deux modèles'],
        },
        {
            'titre': 'Brancher, chiffrer, arbitrer',
            'fil': 'relier le modèle aux documents de l\'entreprise sans sur-partage, puis décider par écrit.',
            'lignes': [
                ('08:00-10:00', '120 min', 'Brancher sur l\'entreprise (O5)', 'Constituer un fonds documentaire maîtrisé, y connecter le moteur ; question dont la réponse n\'existe que dans ces documents ; vérifier la source citée ; le sur-partage.', 'Atelier guidé + contrôle croisé.', 'Fonds documentaire fictif.'),
                PAUSE_MATIN,
                ('10:15-12:00', '105 min', 'Ce que le local ne sait pas faire', 'Raisonnement long, actualité, volumes, langues rares ; architecture mixte ; continuité : mises à jour, sauvegarde, reprise.', 'Apport + étude de cas.', 'Matrice local / distant.'),
                DEJEUNER,
                ('13:00-13:15', '15 min', 'Réveil pédagogique', 'Trois questions de reprise.', 'Oral collectif.', '-'),
                ('13:15-15:00', '105 min', 'Coût réel et registre (O6, O7)', 'Deux colonnes sur 36 mois avec ses chiffres ; dépendance tarifaire contre obsolescence ; entrée de registre (RGPD art. 30) ; mesures de sécurité (art. 32).', 'Calcul guidé + rédaction.', 'Tableur, modèle d\'entrée de registre.'),
                PAUSE_APREM,
                ('15:15-17:00', '105 min', 'Note d\'arbitrage et évaluation (O8)', 'Note d\'une page ; présentation et réponse à deux objections ; quiz de 10 questions ; plan à 30 jours.', 'Mise en situation notée.', 'Grille critériée, quiz.'),
            ],
            'livrables': ['recherche documentaire locale contrôlée', 'coût complet sur 36 mois', 'entrée de registre', 'note d\'arbitrage'],
        },
    ],
    'moyens': MOYENS_BASE + [
        'Postes avec droits d\'administration ; machine de secours équipée apportée par le formateur.',
        'Modèles téléchargés avant la session ; fonds documentaire fictif fourni.',
        'Possibilité de couper physiquement le réseau dans la salle.',
    ],
    'grille': [
        ['1. Trajets de données', 'Confusion', 'Partiel', '8 situations sur 10', 'Explique les cas limites'],
        ['2. Installation', 'Échec', 'Avec aide', 'Autonome en moins de 30 min', 'Aide un pair'],
        ['3. Preuve réseau coupé', 'Absente', 'Moteur seul', 'Chaîne complète prouvée', 'Commentée et reproductible'],
        ['4. Choix du modèle', 'Au hasard', 'Sur la taille annoncée', 'Mesuré et justifié', 'Seuil d\'usage argumenté'],
        ['5. Fonds documentaire', 'Dossier trop large', 'Droits non vérifiés', 'Périmètre maîtrisé, source vérifiée', 'Procédure de mise à jour'],
        ['6. Coût sur 36 mois', 'Absent', 'Incomplet', 'Deux colonnes complètes', 'Hypothèses et risques datés'],
        ['7. Registre et sécurité', 'Absent', 'Incomplet', 'Entrée complète + mesures art. 32', 'Revue planifiée'],
        ['8. Note d\'arbitrage', 'Absente', 'Sans recommandation', 'Recommandation tranchée + conditions', 'Résiste aux objections'],
    ],
    'seuil': '16/24 minimum, avec au moins 2/3 sur les critères 3, 5 et 7. Une installation rapide ne compense pas une preuve absente ou un registre manquant.',
    'seuil_points': '16/24', 'critiques': '3, 5 et 7',
    'suivi': suivi_standard(2, '« Où part la donnée ? », installation, preuve réseau coupé', 'note d\'arbitrage'),
    'quiz': [
        ('Un modèle « local » signifie que…', ['A. l\'éditeur est français', 'B. le calcul se fait sur votre machine, sans appel extérieur', 'C. il est gratuit', 'D. il est plus intelligent'], 'B', 'Local décrit où le calcul a lieu.'),
        ('Pourquoi télécharger les modèles avant la session ?', ['A. Par habitude', 'B. Ils pèsent plusieurs gigaoctets et le réseau du jour J ne suffit pas', 'C. C\'est obligatoire', 'D. Pour l\'éditeur'], 'B', 'L\'erreur qui gâche un déploiement.'),
        ('Le moteur est local, l\'interface ajoutée envoie des statistiques. La solution est-elle « sans donnée sortante » ?', ['Oui', 'Non'], 'Non', 'La preuve porte sur toute la chaîne.'),
        ('Au-delà de quel délai de réponse l\'utilisateur abandonne-t-il le plus souvent l\'outil ?', ['A. 1 seconde', 'B. 10 secondes', 'C. 2 minutes', 'D. Jamais'], 'B', 'Repère utilisé pour choisir la taille de modèle.'),
        ('Comment choisir la taille du modèle ?', ['A. Le plus grand possible', 'B. Selon la vitesse ET la qualité mesurées sur la machine cible', 'C. Le plus récent', 'D. Au hasard'], 'B', 'Le nombre de paramètres annoncé ne suffit pas.'),
        ('Vrai ou faux : une IA locale est hors RGPD.', ['Vrai', 'Faux'], 'Faux', 'Un traitement local reste un traitement : registre et sécurité s\'appliquent.'),
        ('Quel risque apparaît en branchant tout le serveur de fichiers ?', ['A. Aucun', 'B. Le modèle peut citer les dossiers du personnel', 'C. Le modèle ralentit', 'D. L\'éditeur voit tout'], 'B', 'Le sur-partage revient par la fenêtre.'),
        ('Que doit comporter l\'entrée de registre ?', ['A. Finalité, données, durée, destinataires, mesures de sécurité', 'B. Le prix du matériel', 'C. Le nom du modèle seulement', 'D. Rien'], 'A', 'RGPD article 30.'),
        ('Que compare le coût sur 36 mois ?', ['A. Matériel + temps interne + maintenance face à l\'abonnement', 'B. Seulement l\'abonnement', 'C. Seulement le matériel', 'D. Rien'], 'A', 'Le coût complet intègre ce qui ne se voit pas.'),
        ('Une note d\'arbitrage crédible…', ['A. ne dit que les avantages', 'B. dit aussi ce que la solution ne fera pas', 'C. évite de conclure', 'D. fait dix pages'], 'B', 'Dire les limites rend la recommandation crédible.'),
    ],
    'validation': [
        ['Comprendre les trajets', 'Atelier « Où part la donnée ? »', 'Atelier', 'Score ≥ 2 au critère 1'],
        ['Installer et prouver', 'Installation + preuve', 'Démonstration en direct', 'Score ≥ 2 aux critères 2 et 3'],
        ['Choisir et brancher', 'Comparatif + recherche contrôlée', 'Production', 'Score ≥ 2 aux critères 4 et 5'],
        ['Chiffrer et documenter', 'Coût 36 mois + registre', 'Dépôt', 'Score ≥ 2 aux critères 6 et 7'],
        ['Arbitrer', 'Note d\'une page', 'Soutenance', 'Score ≥ 2 au critère 8'],
    ],
    'defi': {
        'intro': 'Vous préparez l\'arbitrage pour votre structure, ou pour le cas de secours : un cabinet comptable de Saint-Pierre qui veut résumer ses lettres de mission sans les envoyer à l\'extérieur.',
        'etapes': [
            'Montrer où part la donnée dans la solution actuelle.',
            'Démontrer, réseau coupé, que la solution locale ne fait rien sortir.',
            'Présenter le modèle retenu, chronomètre à l\'appui.',
            'Présenter le coût sur 36 mois et l\'entrée de registre.',
            'Soutenir la note d\'arbitrage et répondre à deux objections.',
        ],
    },
    'annexes': [
        {'titre': 'Gestes techniques de référence', 'tableau': (['Geste', 'Ce que l\'on fait'], [
            ['LOC-G1', 'Installer le moteur, vérifier la version, télécharger, lancer et lister un modèle.'],
            ['LOC-G2', 'Vérifier l\'écoute en local, couper le réseau, tester, rétablir, contrôler.'],
            ['LOC-G3', 'Relever mémoire et carte graphique ; chronométrer deux modèles.'],
            ['LOC-G4', 'Constituer le fonds documentaire et y connecter le moteur.'],
            ['LOC-G5', 'Chiffrer sur 36 mois en deux colonnes.'],
            ['LOC-G6', 'Rédiger l\'entrée de registre et les mesures de sécurité.'],
        ], [1, 3])},
        {'titre': 'Trame de la note d\'arbitrage', 'puces': [
            'Le besoin, en une phrase, et les données concernées.',
            'Option locale, option distante : ce que chacune expose, coûte et permet.',
            'Recommandation tranchée.',
            'Conditions : matériel, responsable, sauvegarde, mises à jour, seuil de révision.',
            'Ce que la solution ne fera pas.',
        ]},
    ],
    'accessibilite': 'Supports en corps 16, terminal configurable en fort contraste et corps majoré, adaptation du rythme, pauses supplémentaires, reformulation écrite des consignes, binômage sur les ateliers techniques ; machine de secours pour le stagiaire dont le poste ne suit pas. Aucun aménagement n\'est facturé et aucune information médicale n\'est demandée.',
    'sources': [
        'Ollama, documentation — https://ollama.com/',
        'CNIL, « La sécurité des données personnelles » (guide) — https://www.cnil.fr/',
        'Règlement (UE) 2016/679, articles 30 et 32 — https://eur-lex.europa.eu/',
    ],
}
