from commun import DEJEUNER, MOYENS_BASE, PAUSE_APREM, PAUSE_MATIN, VERSION, suivi_standard

F = {
    'ref': 'FOR-0010', 'fichier': 'programme-detaille-for-0010-emailing-ia.pdf', 'nom_affiche': 'Programme detaille - FOR-0010 - Emailing IA.pdf',
    'titre': 'Emailing IA : Rédiger des courriels et des séquences qui obtiennent une réponse',
    'nom': 'Emailing IA',
    'promesse_titre': 'Rédiger des courriels et des séquences qui obtiennent une réponse',
    'promesse': "À la fin de la journée, chaque participant repart avec son fichier de contacts assaini et conforme, un courriel type rédigé avec l'IA, une séquence de trois courriels prête à programmer et un tableau de bord à quatre indicateurs.",
    'format_court': 'Présentiel - 1 jour', 'jours': 1, 'heures': 8, 'validation_courte': '1 séquence complète',
    'inter': '790', 'intra': '2 500', 'version': VERSION,
    'public_court': 'dirigeants de TPE-PME, indépendants, commerciaux, chargés de communication.',
    'public': 'Dirigeants de TPE-PME, indépendants, commerciaux, fonctions administratives et chargés de communication qui écrivent à des clients ou à des prospects — campagne ou courriels quotidiens.',
    'prerequis': 'Utilisation courante d\'une messagerie et d\'un tableur simple. Aucune compétence technique ni expérience du marketing. Venir avec son fichier de contacts (s\'il existe), un courriel déjà envoyé et l\'offre à promouvoir.',
    'materiel': 'Un ordinateur portable par stagiaire (inter : apporter le sien), avec accès à sa messagerie professionnelle.',
    'production': 'Un fichier de contacts segmenté avec sa colonne « origine », un courriel type et la consigne qui l\'a produit, une séquence de trois courriels datée, la fiche de registre « prospection » et un tableau de bord à quatre indicateurs.',
    'outils': 'Assistant d\'IA générative (compte professionnel ; voie européenne Mistral Le Chat possible), tableur, outil d\'emailing de démonstration (ex. Brevo), messagerie de test.',
    'financements': 'OPCO, plan de développement des compétences, France Travail (AIF), Région Réunion',
    'positionnement': {
        'idee': "Un courriel qui obtient une réponse commence par le bon destinataire. On assainit le fichier avant d'écrire, on écrit avec l'IA mais on relit tout, et on mesure avant de recommencer.",
        'intro': 'La journée suit l\'ordre réel d\'une campagne :',
        'points': [
            'À qui : un fichier propre, dont chaque contact a une origine connue et une base légale.',
            'Quoi : objet, accroche, corps, appel à l\'action — rédigés avec l\'IA à partir d\'une consigne structurée.',
            'Quand : une séquence de trois courriels, avec un rythme et une sortie de séquence.',
            'Comment être reçu : expéditeur identifié, domaine authentifié, lien de désinscription.',
            'Et après : quatre indicateurs, et ce que l\'on corrige selon chacun.',
        ],
        'vigilance': "Les règles de prospection ne sont pas les mêmes envers un particulier (consentement préalable) et envers un professionnel (information et droit d'opposition). On ne donne jamais à l'IA un fichier clients nominatif.",
    },
    'vocabulaire': [
        ['Objet', 'La courte phrase lue dans la boîte de réception avant l\'ouverture.'],
        ['Texte d\'aperçu', 'La phrase affichée à côté de l\'objet ; elle complète l\'objet et donne envie d\'ouvrir.'],
        ['Appel à l\'action', 'Le bouton ou la phrase qui dit précisément quoi faire : « Je réserve mon créneau ».'],
        ['Séquence', 'Plusieurs courriels envoyés dans un ordre et un rythme définis, avec une règle d\'arrêt.'],
        ['Délivrabilité', 'La capacité d\'un courriel à arriver dans la boîte de réception, et non dans les indésirables.'],
        ['Segment', 'Un groupe de contacts qui partagent un besoin ou une situation.'],
        ['Opposition', 'Le droit de ne plus recevoir de messages, exercé par un lien de désinscription simple et gratuit.'],
        ['Taux de plainte', 'La part des destinataires qui signalent le message comme indésirable ; au-delà de 0,1 %, l\'alerte est sérieuse.'],
    ],
    'objectifs': [
        ['O1', 'Constituer', 'Assainir et segmenter une base de contacts conforme au RGPD et aux règles de la prospection électronique (B2B / B2C).', 'Fichier segmenté avec colonne « origine » + fiche de registre « prospection ».'],
        ['O2', 'Rédiger', 'Rédiger avec l\'IA un courriel professionnel qui obtient une réponse : objet, accroche, corps, appel à l\'action.', 'Courriel type relu, aucun fait inventé, consigne réutilisable.'],
        ['O3', 'Séquencer', 'Concevoir une séquence de trois courriels, en régler le rythme et la sortie.', 'Séquence datée, règle d\'arrêt écrite.'],
        ['O4', 'Paramétrer', 'Paramétrer l\'envoi pour être reçu : expéditeur identifié, authentification, désinscription.', 'Checklist d\'envoi complétée, courriel de test reçu.'],
        ['O5', 'Mesurer', 'Lire les indicateurs réels (ouverture, clic, désinscription, plainte) et décider de la correction.', 'Tableau de bord à quatre indicateurs et décision justifiée sur un cas.'],
    ],
    'jours_detail': [
        {
            'titre': None,
            'fil': 'passer d\'un fichier en désordre à une séquence prête à programmer, conforme et mesurable.',
            'lignes': [
                ('08:00-08:30', '30 min', 'Séquence 0 « La boîte de réception »', 'Pourquoi 9 courriels sur 10 ne sont jamais lus ; attentes ; information RGPD et transparence IA.', 'Projection d\'une boîte réelle anonymisée + vote.', 'Diaporama, liste d\'objets imprimée.'),
                ('08:30-09:15', '45 min', 'Ce que la loi permet (O1)', 'Prospection B2B / B2C : consentement, information, opposition ; identité de l\'annonceur.', 'Études de cas + quiz flash.', 'Cas B2C, B2B, associatif.'),
                ('09:15-10:00', '45 min', 'Assainir et segmenter son fichier (O1)', 'Origine de chaque contact, doublons, segments utiles ; fiche de registre « prospection ».', 'Atelier individuel sur son fichier (ou fichier fictif).', 'Tableur, fiche de registre.'),
                PAUSE_MATIN,
                ('10:15-11:00', '45 min', 'La structure qui fonctionne (O2)', 'Objet, accroche, corps, appel à l\'action ; analyse de deux courriels.', 'Apport dialogué + annotation collective.', 'Courriels annotés.'),
                ('11:00-12:00', '60 min', 'Écrire avec l\'IA (O2)', 'La consigne : rôle, contexte, destinataire, objectif, contraintes, exemple ; relire ce que l\'IA invente ; ce qu\'on ne lui donne jamais.', 'Démonstration comparée + atelier en binômes.', 'Assistant d\'IA (compte professionnel).'),
                DEJEUNER,
                ('13:00-14:00', '60 min', 'La séquence de trois courriels (O3)', 'Rythme, relance, sortie de séquence ; « Sept mots » pour l\'objet.', 'Atelier individuel accompagné.', 'Gabarit de séquence.'),
                ('14:00-15:00', '60 min', 'Être reçu (O4)', 'Expéditeur identifié, authentification du domaine (SPF, DKIM, DMARC expliqués simplement), contenu, lien de désinscription ; traiter une opposition.', 'Démonstration + jeu de rôle « La demande embarrassante ».', 'Outil d\'emailing de démonstration.'),
                PAUSE_APREM,
                ('15:15-16:00', '45 min', 'Mesurer et corriger (O5)', 'Ouverture, clic, désinscription, plainte : ce qu\'on corrige selon chacun ; qui signe quand l\'IA écrit.', 'Lecture de tableaux de bord réels anonymisés.', 'Tableau de bord type.'),
                ('16:00-16:45', '45 min', 'Évaluation finale', 'Séquence complète et fiche de registre notées sur la grille ; quiz de 10 questions.', 'Production autonome + quiz.', 'Grille critériée, quiz.'),
                ('16:45-17:00', '15 min', 'Plan d\'action à 30 jours', 'Premier envoi, date, indicateur à suivre ; satisfaction à chaud.', 'Engagement individuel écrit.', 'Fiche plan d\'action.'),
            ],
            'livrables': ['fichier assaini et segmenté', 'fiche de registre « prospection »', 'courriel type + consigne', 'séquence de trois courriels', 'tableau de bord à 4 indicateurs'],
        },
    ],
    'moyens': MOYENS_BASE + [
        'Un ordinateur portable par participant, accès à sa messagerie professionnelle et à un assistant d\'IA avec un compte professionnel.',
        'Un compte d\'emailing de démonstration sans contacts réels et une liste d\'adresses de test autorisées.',
        'Un fichier de contacts fictif pour les participants qui n\'apportent pas le leur.',
    ],
    'grille': [
        ['1. Fichier', 'Contacts sans origine', 'Origine partielle', 'Origine et segment pour chaque contact', 'Base légale justifiée par segment'],
        ['2. Conformité', 'Risque majeur (B2C sans consentement)', 'Mentions incomplètes', 'Identité, opposition et registre traités', 'Justification selon le contexte'],
        ['3. Consigne IA', 'Demande vague', 'Quelques contraintes', 'Consigne structurée et réutilisable', 'Itérations pilotées par critères'],
        ['4. Courriel', 'Confus ou hors cible', 'Générique', 'Bénéfice et appel à l\'action clairs', 'Voix distinctive et concise'],
        ['5. Vérification des faits', 'Inventions conservées', 'Vérification partielle', 'Tous les faits vérifiés', 'Sources notées'],
        ['6. Séquence', 'Absente', 'Courriels sans rythme', 'Trois courriels datés, sortie prévue', 'Variantes selon la réaction'],
        ['7. Délivrabilité', 'Non traitée', 'Partielle', 'Checklist d\'envoi complète', 'Test reçu sur deux messageries'],
        ['8. Mesure', 'Aucun indicateur', 'Un indicateur', 'Quatre indicateurs + décision', 'Décision argumentée et datée'],
    ],
    'seuil': '16/24 minimum, avec au moins 2/3 sur les critères 2, 5 et 7. Un beau courriel ne compense jamais un fichier non conforme.',
    'seuil_points': '16/24', 'critiques': '2, 5 et 7',
    'suivi': suivi_standard(1, 'Observation des ateliers de rédaction + retour entre pairs', 'séquence complète'),
    'quiz': [
        ('Que faut-il faire avant de rédiger un courriel de prospection ?', ['A. Choisir les couleurs', 'B. Connaître l\'origine et le segment des contacts', 'C. Acheter un fichier', 'D. Fixer l\'heure d\'envoi'], 'B', 'Le fichier précède le texte.'),
        ('Envers un particulier, la prospection par courriel exige en principe…', ['A. son consentement préalable', 'B. un simple envoi', 'C. une facture', 'D. un appel téléphonique'], 'A', 'B2C : consentement préalable, sauf produits analogues pour un client existant.'),
        ('Envers un professionnel, il faut au minimum…', ['A. son accord écrit', 'B. l\'informer et lui permettre de s\'opposer simplement, pour un message lié à sa fonction', 'C. rien', 'D. un contrat'], 'B', 'B2B : information et droit d\'opposition, message en rapport avec sa profession.'),
        ('Vrai ou faux : on peut coller son fichier clients dans l\'IA pour personnaliser plus vite.', ['Vrai', 'Faux'], 'Faux', 'Minimisation : on ne donne pas de données nominatives inutiles à l\'outil.'),
        ('Quel appel à l\'action est le plus précis ?', ['A. Cliquez ici', 'B. En savoir plus', 'C. Je réserve mon diagnostic de 20 minutes', 'D. Continuer'], 'C', 'Le verbe et le résultat attendu sont explicites.'),
        ('L\'IA écrit « +40 % de ventes garanties ». Que faire ?', ['A. Garder, c\'est vendeur', 'B. Supprimer ou remplacer par un fait vérifié', 'C. Mettre en gras', 'D. Ajouter un émoji'], 'B', 'Une allégation non vérifiée est une pratique commerciale trompeuse.'),
        ('Que doit contenir chaque courriel de prospection ?', ['A. Une pièce jointe', 'B. L\'identité de l\'expéditeur et un lien de désinscription', 'C. Cinq images', 'D. Un code promo'], 'B', 'Identification et opposition simple sont obligatoires.'),
        ('Une séquence de trois courriels doit prévoir…', ['A. une sortie dès que le contact répond ou se désinscrit', 'B. un envoi par jour', 'C. le même texte trois fois', 'D. aucune règle'], 'A', 'La règle d\'arrêt protège la relation et la délivrabilité.'),
        ('Le taux de plainte dépasse 0,3 %. Quelle décision ?', ['A. Envoyer plus', 'B. Suspendre, revoir le segment et la fréquence', 'C. Changer l\'objet seulement', 'D. Ignorer'], 'B', 'La plainte révèle un problème de ciblage ou de consentement.'),
        ('Quand l\'IA a rédigé le courriel, qui en est responsable ?', ['A. L\'éditeur de l\'IA', 'B. L\'expéditeur', 'C. Personne', 'D. Le destinataire'], 'B', 'L\'expéditeur signe et répond du contenu.'),
    ],
    'validation': [
        ['Constituer un fichier conforme', 'Fichier segmenté + fiche de registre', 'Dépôt', 'Score ≥ 2 aux critères 1 et 2'],
        ['Rédiger avec l\'IA', 'Consigne + courriel type', 'Production', 'Score ≥ 2 aux critères 3 à 5'],
        ['Concevoir une séquence', 'Séquence datée', 'Production', 'Score ≥ 2 au critère 6'],
        ['Paramétrer l\'envoi', 'Checklist + test reçu', 'Observation directe', 'Score ≥ 2 au critère 7'],
        ['Mesurer et corriger', 'Tableau de bord + décision', 'Étude de cas', 'Score ≥ 2 au critère 8'],
    ],
    'defi': {
        'intro': 'Vous préparez une campagne réelle de votre activité, ou le cas de secours : un traiteur de Saint-Paul qui relance ses clients entreprises avant les fêtes.',
        'etapes': [
            'Présenter le segment visé, l\'origine des contacts et la base légale retenue.',
            'Montrer la consigne donnée à l\'IA et la correction la plus importante que vous avez faite.',
            'Présenter la séquence de trois courriels : objets, dates, règle de sortie.',
            'Montrer la checklist d\'envoi et le courriel de test reçu.',
            'Dire quel indicateur vous suivrez en premier, et ce que vous ferez s\'il est mauvais.',
        ],
    },
    'annexes': [
        {'titre': 'Modèle de consigne pour l\'IA', 'encart': ('CONSIGNE', "Tu es rédacteur commercial pour [ENTREPRISE], à La Réunion. Destinataire : [SEGMENT, sans nom de personne]. Objectif : obtenir [ACTION UNIQUE]. Ton : [3 ADJECTIFS]. Faits vérifiés à utiliser : [FAITS]. N'invente aucun chiffre, prix, date ou témoignage ; signale ce qui manque. Propose 3 objets de 7 mots maximum, 3 textes d'aperçu, puis un courriel de 120 mots maximum avec un seul appel à l'action.")},
        {'titre': 'Checklist avant envoi', 'puces': [
            'Chaque contact a une origine connue et un segment ; la base légale est notée au registre.',
            'L\'objet est fidèle au contenu ; le texte d\'aperçu le complète.',
            'Tous les faits, prix et dates ont été vérifiés.',
            'Un seul appel à l\'action principal, précis.',
            'Identité de l\'expéditeur et lien de désinscription présents et testés.',
            'Domaine d\'envoi authentifié ; courriel de test reçu sur deux messageries.',
            'La règle de sortie de séquence est paramétrée.',
        ]},
    ],
    'accessibilite': 'Formation accessible aux personnes en situation de handicap ; aucun justificatif médical n\'est demandé. Spécifique à cette formation : la liste des objets projetés est remise sur papier en corps 16 avant la projection, le chronomètre peut être supprimé, chaque objet est lu à voix haute, les votes peuvent se faire par écrit et le jeu de rôle « La demande embarrassante » peut être traité entièrement à l\'écrit.',
    'sources': [
        'CNIL, « La prospection commerciale par courrier électronique » — https://www.cnil.fr/fr/la-prospection-commerciale-par-courrier-electronique',
        'Code des postes et des communications électroniques, article L.34-5 — https://www.legifrance.gouv.fr/',
        'Code de la consommation, article L.121-2 (pratiques commerciales trompeuses) — https://www.legifrance.gouv.fr/',
    ],
}
