from commun import DEJEUNER, MOYENS_BASE, PAUSE_APREM, PAUSE_MATIN, VERSION, suivi_standard

F = {
    'ref': 'FOR-0014', 'fichier': 'programme-detaille-for-0014-seminaire-dirigeants-ia.pdf', 'nom_affiche': 'Programme detaille - FOR-0014 - Seminaire dirigeants IA.pdf',
    'titre': "Séminaire dirigeants IA : Choisir les 3 tâches que l'IA fera pour vous (résidentiel, 2 jours)",
    'nom': 'Séminaire dirigeants IA',
    'promesse_titre': "Choisir les 3 tâches que l'IA fera pour vous — résidentiel, à huis clos",
    'promesse': "En deux jours à huis clos, chaque dirigeant choisit les trois tâches que l'IA prendra en charge, les qualifie au regard de l'IA Act, fixe leur niveau d'autonomie et repart avec son plan d'agents, son tableau de responsabilité, sa charte d'usage et son budget à 12 mois.",
    'format_court': 'Résidentiel - 2 jours', 'jours': 2, 'heures': 16, 'validation_courte': 'Plan d\'agents soutenu',
    'inter': '990', 'intra': '2 900', 'version': VERSION,
    'public_court': 'dirigeants de TPE-PME réunionnaises de 3 à 50 salariés, décisionnaires du budget.',
    'public': 'Dirigeants, gérants, directeurs généraux et associés de TPE-PME réunionnaises de 3 à 50 salariés, seuls décisionnaires de l\'engagement budgétaire. Un dirigeant par entreprise ; deux concurrents directs ne sont jamais réunis sur la même session (règle écrite dans la convention).',
    'prerequis': 'Aucun prérequis technique. Venir avec la liste de ses cinq tâches les plus chronophages, son chiffre d\'affaires, son effectif et la liste des outils numériques en place (demandés à l\'inscription).',
    'materiel': 'Matériel précisé à l\'inscription (à confirmer par la direction : un ordinateur portable est utile pour suivre les démonstrations comparées).',
    'production': 'Plan d\'agents de deux pages, tableau de responsabilité nominatif, charte d\'usage de l\'IA d\'une page, budget et calendrier à 12 mois avec critère d\'arrêt.',
    'outils': 'Démonstrations en voie américaine, européenne et locale (réseau coupé) ; gabarits de plan, de tableau de responsabilité, de charte et de budget.',
    'financements': 'OPCO, plan de développement des compétences. L\'hébergement est contracté directement avec l\'établissement et n\'entre pas dans le coût pédagogique',
    'positionnement': {
        'idee': "Un dirigeant n'a pas besoin d'apprendre un outil : il doit décider quoi confier à l'IA, avec quel risque, qui en répond et combien cela coûte. Le séminaire produit ces décisions, par écrit.",
        'intro': 'Le séminaire suit l\'ordre d\'une décision d\'investissement :',
        'points': [
            'Choisir : trois tâches chiffrées en heures par mois.',
            'Qualifier : interdit, haut risque, transparence ou sans obligation particulière.',
            'Encadrer : niveau d\'autonomie fixé sur le coût de l\'erreur, point d\'arrêt humain.',
            'Planifier : un seul agent en production les trois premiers mois.',
            'Engager : responsable nommé, charte, budget, critère d\'abandon écrit à l\'avance.',
        ],
        'vigilance': "Le tri de candidatures et l'évaluation des salariés relèvent du haut risque (IA Act, annexe III). Une décision produisant un effet significatif sur une personne ne peut être entièrement automatisée (RGPD art. 22).",
    },
    'vocabulaire': [
        ['Assistant', 'Une IA qui répond quand on lui demande.'],
        ['Agent', 'Une IA qui exécute des actions, parfois sans humain devant.'],
        ['Niveau d\'autonomie', 'Propose · exécute sous accord · exécute et rend compte · décide seul.'],
        ['Point d\'arrêt humain', 'L\'étape où une personne doit valider avant que l\'agent continue.'],
        ['Haut risque', 'Catégorie de l\'IA Act (annexe III) soumise à des obligations renforcées, dont le recrutement.'],
        ['Tableau de responsabilité', 'Une ligne par système d\'IA, un nom par ligne : qui en répond.'],
        ['Charte d\'usage', 'La règle d\'une page : ce qui est permis, interdit, et qui arbitre.'],
        ['Critère d\'arrêt', 'La condition, écrite à l\'avance, qui déclenche l\'abandon du projet.'],
    ],
    'objectifs': [
        ['O1', 'Analyser', 'Identifier les trois tâches dont l\'automatisation dégagerait le plus de temps de dirigeant.', 'Trois tâches chiffrées en heures par mois et classées.'],
        ['O2', 'Évaluer', 'Qualifier chaque tâche au regard de l\'IA Act.', 'Trois qualifications avec l\'article invoqué.'],
        ['O3', 'Évaluer', 'Fixer le niveau d\'autonomie acceptable selon le coût de l\'erreur.', 'Niveau attribué, coût chiffré en euros et en réputation.'],
        ['O4', 'Créer', 'Construire le plan d\'agents : périmètre, séquence, point d\'arrêt, responsable.', 'Plan de deux pages soutenu face à deux objections.'],
        ['O5', 'Évaluer', 'Arbitrer entre solution américaine, européenne et locale avec la grille des cinq critères.', 'Arbitrage écrit et daté, conditions de révision.'],
        ['O6', 'Appliquer', 'Désigner qui répond de chaque système d\'IA déployé.', 'Tableau nominatif sans case vide.'],
        ['O7', 'Créer', 'Rédiger la charte d\'usage de l\'IA de l\'entreprise.', 'Charte d\'une page : permis, interdit, qui arbitre.'],
        ['O8', 'Évaluer', 'Établir budget, calendrier à 12 mois et seuil d\'arrêt.', 'Budget chiffré, jalons datés, critère d\'abandon écrit.'],
    ],
    'jours_detail': [
        {
            'titre': 'Choisir et qualifier',
            'fil': 'passer de « l\'IA, il faudrait s\'y mettre » à trois tâches chiffrées, qualifiées et dont le risque est connu.',
            'lignes': [
                ('08:00-10:00', '120 min', 'Où vous en êtes vraiment (O1)', 'Séquence 0 : les cinq tâches qui mangent les semaines ; ce qui a déjà été tenté ; les trois erreurs de déploiement les plus coûteuses en TPE-PME.', 'Tour de table à huis clos + chiffrage individuel.', 'Fiche « 5 tâches », paperboard.'),
                PAUSE_MATIN,
                ('10:15-12:00', '105 min', 'Qualifier avant d\'acheter (O2)', 'Assistant, agent, système ; IA Act : interdit (art. 5), haut risque (annexe III), transparence (art. 50) ; le cas du tri de candidatures.', 'Atelier : trois tâches qualifiées, article à l\'appui.', 'Grille de qualification.'),
                DEJEUNER,
                ('13:00-13:15', '15 min', 'Réveil pédagogique', 'Trois questions de reprise, sans note.', 'Oral collectif.', '-'),
                ('13:15-15:00', '105 min', 'Le coût de l\'erreur (O3)', 'Quatre niveaux d\'autonomie ; chiffrer l\'erreur en euros et en réputation ; placer le point d\'arrêt avant la première action irréversible.', 'Atelier sur son propre cas.', 'Fiche « coût de l\'erreur ».'),
                PAUSE_APREM,
                ('15:15-17:00', '105 min', 'Démonstrations comparées (O5)', 'La même tâche en voie américaine, européenne, puis locale réseau coupé ; grille : coût complet, souveraineté, dépendance, compétence, réversibilité.', 'Démonstration + arbitrage provisoire noté.', 'Postes de démonstration, grille d\'arbitrage.'),
            ],
            'livrables': ['trois tâches chiffrées et qualifiées', 'niveaux d\'autonomie justifiés', 'arbitrage provisoire'],
        },
        {
            'titre': 'Planifier et s\'engager',
            'fil': 'transformer les choix de la veille en documents signables : plan, responsables, charte, budget.',
            'lignes': [
                ('08:00-10:00', '120 min', 'Le plan d\'agents (O4)', 'Périmètre, séquence, point d\'arrêt, responsable ; un seul agent en production les trois premiers mois ; relecture par un autre dirigeant.', 'Rédaction individuelle accompagnée + relecture croisée.', 'Gabarit de plan.'),
                PAUSE_MATIN,
                ('10:15-12:00', '105 min', 'Qui signe ? (O6, O7)', 'Tableau de responsabilité ; RGPD art. 22 ; registre et inventaire des systèmes ; rédaction de la charte d\'usage.', 'Atelier guidé.', 'Gabarits tableau et charte.'),
                DEJEUNER,
                ('13:00-13:15', '15 min', 'Réveil pédagogique', 'Trois questions de reprise.', 'Oral collectif.', '-'),
                ('13:15-15:00', '105 min', 'Budget, calendrier, seuil d\'arrêt (O8)', 'Licences, temps interne, formation, maintenance ; jalons ; critère d\'abandon ; ce que finance l\'opérateur de compétences.', 'Calcul guidé.', 'Tableur de budget.'),
                PAUSE_APREM,
                ('15:15-17:00', '105 min', 'Soutenance et engagement', 'Plan présenté en 8 minutes, deux objections ; livrables notés ; quiz de 10 questions ; première action à 30 jours et son responsable.', 'Soutenance notée.', 'Grille critériée, quiz.'),
            ],
            'livrables': ['plan d\'agents', 'tableau de responsabilité', 'charte d\'usage', 'budget à 12 mois'],
        },
    ],
    'moyens': MOYENS_BASE + [
        'Salle de séminaire en établissement hôtelier, à huis clos ; accessibilité vérifiée avant confirmation.',
        'Postes de démonstration pour les voies américaine, européenne et locale.',
        'Gabarits papier et numériques des quatre livrables.',
    ],
    'grille': [
        ['1. Choix des tâches', 'Tâches floues', 'Non chiffrées', 'Trois tâches chiffrées et classées', 'Arbitrage argumenté'],
        ['2. Qualification IA Act', 'Absente', 'Sans article', 'Trois qualifications justifiées', 'Anticipe les obligations'],
        ['3. Autonomie', 'Au confort', 'Sans chiffrage', 'Niveau fixé sur le coût de l\'erreur', 'Point d\'arrêt bien placé'],
        ['4. Plan d\'agents', 'Absent', 'Liste d\'envies', 'Plan complet, un agent d\'abord', 'Résiste aux objections'],
        ['5. Arbitrage', 'Aucun', 'Préférence', 'Grille des cinq critères', 'Conditions de révision'],
        ['6. Responsabilité', 'Personne', 'Cases vides', 'Tableau nominatif complet', 'Temps alloué au responsable'],
        ['7. Charte', 'Absente', 'Vague', 'Permis, interdit, arbitre', 'Diffusable dès le retour'],
        ['8. Budget et arrêt', 'Absent', 'Sans critère d\'arrêt', 'Budget, jalons, critère d\'abandon', 'Financement identifié'],
    ],
    'seuil': '16/24 minimum, avec au moins 2/3 sur les critères 2, 3 et 6. Un plan ambitieux sans responsable nommé ni qualification juridique n\'est pas validé.',
    'seuil_points': '16/24', 'critiques': '2, 3 et 6',
    'suivi': suivi_standard(2, 'Qualification et chiffrage sur son cas', 'soutenance du plan'),
    'quiz': [
        ('Combien d\'agents mettre en production les trois premiers mois ?', ['A. Trois', 'B. Un seul', 'C. Autant que possible', 'D. Aucun'], 'B', 'On apprend sur un agent avant d\'en lancer d\'autres.'),
        ('Le tri automatique de candidatures relève…', ['A. d\'aucune obligation', 'B. du haut risque (annexe III)', 'C. des pratiques interdites', 'D. du simple bon sens'], 'B', 'Le recrutement figure à l\'annexe III de l\'IA Act.'),
        ('Sur quoi fixer le niveau d\'autonomie d\'un agent ?', ['A. Le confort d\'usage', 'B. Le coût de l\'erreur', 'C. Le prix de l\'outil', 'D. La mode'], 'B', 'C\'est la règle YEBA.'),
        ('Où placer le point d\'arrêt humain ?', ['A. À la fin', 'B. Juste avant la première action irréversible', 'C. Au début', 'D. Nulle part'], 'B', 'C\'est là qu\'il évite le dommage.'),
        ('Vrai ou faux : une décision produisant un effet significatif sur une personne peut être entièrement automatisée sans garantie.', ['Vrai', 'Faux'], 'Faux', 'RGPD article 22.'),
        ('Ce qui fait le plus souvent échouer un plan d\'agents :', ['A. Le choix du logo', 'B. Aucun responsable nommé, ou sans temps alloué', 'C. Une réunion de trop', 'D. Le prix'], 'B', 'Un projet sans responsable s\'arrête de lui-même.'),
        ('Un critère d\'arrêt s\'écrit…', ['A. après l\'échec', 'B. avant de lancer le projet', 'C. jamais', 'D. par l\'éditeur'], 'B', 'Écrit à l\'avance, il évite l\'acharnement.'),
        ('La grille d\'arbitrage YEBA compare…', ['A. couleur et marque', 'B. coût complet, souveraineté, dépendance, compétence, réversibilité', 'C. la seule vitesse', 'D. le nombre d\'utilisateurs'], 'B', 'Cinq critères, notés sur le cas réel.'),
        ('Le registre des traitements et l\'inventaire des systèmes d\'IA sont…', ['A. le même document', 'B. deux documents, deux logiques', 'C. inutiles', 'D. facultatifs'], 'B', 'Le registre relève du RGPD, l\'inventaire de la gouvernance IA.'),
        ('L\'hébergement du séminaire résidentiel…', ['A. est facturé par l\'organisme de formation', 'B. est contracté directement avec l\'établissement, hors coût pédagogique', 'C. est financé par le CPF', 'D. est gratuit'], 'B', 'Il n\'entre pas dans l\'assiette pédagogique.'),
    ],
    'validation': [
        ['Choisir et qualifier', 'Trois tâches + qualifications', 'Atelier', 'Score ≥ 2 aux critères 1 et 2'],
        ['Encadrer le risque', 'Niveaux d\'autonomie', 'Atelier', 'Score ≥ 2 au critère 3'],
        ['Planifier', 'Plan d\'agents', 'Soutenance', 'Score ≥ 2 aux critères 4 et 5'],
        ['Responsabiliser', 'Tableau + charte', 'Dépôt', 'Score ≥ 2 aux critères 6 et 7'],
        ['Budgéter', 'Budget 12 mois', 'Dépôt', 'Score ≥ 2 au critère 8'],
    ],
    'defi': {
        'intro': 'Vous présentez votre plan d\'agents au groupe, comme à un conseil d\'administration.',
        'etapes': [
            'Les trois tâches retenues, leur gain en heures par mois et leur qualification IA Act.',
            'Le premier agent lancé, son niveau d\'autonomie et son point d\'arrêt.',
            'Le responsable nommé et le temps qui lui est alloué.',
            'Le budget, les jalons et le critère d\'abandon.',
            'Réponse à deux objections du groupe ; 8 minutes au total.',
        ],
    },
    'annexes': [
        {'titre': 'Tableau de responsabilité (modèle)', 'tableau': (['Colonne', 'Ce que l\'on écrit'], [
            ['Système', 'Nom de l\'outil ou de l\'agent, et sa tâche.'], ['Niveau d\'autonomie', 'Propose / sous accord / rend compte / décide seul.'],
            ['Responsable', 'Une personne nommée (jamais « l\'équipe »).'], ['Point d\'arrêt', 'L\'étape validée par un humain.'],
            ['Qualification', 'Interdit / haut risque / transparence / sans obligation particulière.'], ['Revue', 'Date de la prochaine vérification.'],
        ], [1, 3])},
        {'titre': 'Trame de la charte d\'usage (une page)', 'puces': [
            'Ce qui est permis, avec quels outils et quels comptes.',
            'Ce qui ne se saisit jamais (données sensibles, secrets d\'affaires, données nominatives non nécessaires).',
            'La relecture humaine obligatoire avant toute diffusion, et la mention de transparence.',
            'Qui arbitre les cas non prévus, et comment signaler un incident.',
        ]},
    ],
    'accessibilite': 'Supports en corps 16, adaptation du rythme, pauses supplémentaires, reformulation écrite des consignes ; accessibilité de l\'établissement vérifiée avant confirmation. Aménagements sans supplément de prix, sans information médicale demandée.',
    'sources': [
        'Règlement (UE) 2024/1689 (IA Act), article 5, article 50 et annexe III — https://eur-lex.europa.eu/',
        'Règlement (UE) 2016/679 (RGPD), article 22 — https://eur-lex.europa.eu/',
        'CNIL, recommandations sur l\'IA — https://www.cnil.fr/fr/intelligence-artificielle',
    ],
}
