"""Mémo des méthodes de chaque formation (page « Mémo » du livret d'accueil)."""

MEMOS = {
    'FOR-0002': [['Quand / Si / Alors', 'Le déclencheur · la condition · l\'action : on dessine avant de construire'],
                 ['Les 4 critères', 'Fréquence · règles stables · volume · coût de l\'erreur'],
                 ['Tester', 'Le cas normal, puis : donnée absente, doublon, erreur d\'envoi'],
                 ['Sécuriser', 'Identifiants protégés · données minimales · registre à jour'],
                 ['Prouver le gain', 'Temps avant / après · erreurs évitées · coût de l\'outil']],
    'FOR-0003': [['Les 6 principes', 'Licéité · minimisation · exactitude · conservation limitée · sécurité · responsabilité'],
                 ['Le registre', 'Une fiche par traitement : finalité, base légale, données, destinataires, durée, sécurité'],
                 ['Les 3 bacs', 'Je saisis · j\'anonymise d\'abord · je ne saisis jamais'],
                 ['IA Act', 'Interdit · haut risque · transparence (art. 50) · maîtrise de l\'IA (art. 4)'],
                 ['Violation', 'Contenir dans l\'heure · qualifier · notifier la CNIL sous 72 heures si risque']],
    'FOR-0004': [['L\'entretien', 'Préparer · prendre contact · découvrir · argumenter · traiter les objections · conclure'],
                 ['Découvrir', 'Questions ouvertes · écoute active · reformulation · le besoin avec SES mots'],
                 ['Argumenter', 'Caractéristique › avantage › bénéfice pour CE client'],
                 ['Objections', 'Accueillir · questionner · reformuler · répondre'],
                 ['Le prix', 'L\'annoncer sans s\'excuser, puis se taire']],
    'FOR-0006': [['P1 Périmètre', 'Que voit l\'assistant, et est-ce normal ?'], ['P2 Prompt', 'Objectif · contexte · sources désignées · format'],
                 ['P3 Production', 'Des processus entiers, avec relecture humaine tracée'], ['P4 Preuve', 'Ce que j\'ai vérifié, ce que j\'ai écarté, et pourquoi'],
                 ['Les 4 correctifs', 'Contexte · exemple · périmètre · question en retour']],
    'FOR-0008': [['Les 3 casquettes', 'Organiser · accompagner · décider'], ['Déléguer', 'Objectif · moyens · échéance · points de contrôle'],
                 ['Recadrer en 4 temps', 'Faits · impact · attente · engagement'], ['Reconnaître', 'Un feedback positif précis, au bon moment'],
                 ['Le point individuel', 'Régulier, court, préparé des deux côtés']],
    'FOR-0009': [['Les 4 phrases', 'Qui êtes-vous · que proposez-vous · pour qui · que doit faire le visiteur'],
                 ['Les 4 leviers', 'Compléter le contexte · montrer un exemple · réduire la demande · demander ce qui manque'],
                 ['Chasse aux inventions', 'Tarifs, horaires, labels : tout ce que l\'outil a écrit seul est vérifié'],
                 ['Conformité', 'Mentions légales · confidentialité · traceurs · formulaire minimal'], ['Accessibilité', 'Contrastes · titres · liens explicites · textes alternatifs']],
    'FOR-0010': [['Le fichier d\'abord', 'Origine de chaque contact · segment · base légale'], ['La structure', 'Objet · accroche · corps · appel à l\'action'],
                 ['La consigne IA', 'Rôle · contexte · destinataire · objectif · contraintes · exemple'], ['La séquence', 'Trois courriels · un rythme · une règle de sortie'],
                 ['Les 4 indicateurs', 'Ouverture · clic · désinscription · plainte']],
    'FOR-0011': [['Les 4 C', 'Casquette · Contexte · Cadre · Contrôle'], ['Les 3 bacs', 'Je saisis · j\'anonymise d\'abord · je ne saisis jamais'],
                 ['Vérifier', 'Le défaut · la source de vérification · la trace'], ['Qui voit quoi ?', 'Le sur-partage vient des droits d\'accès, jamais de l\'IA'],
                 ['La règle YEBA', 'Un chiffre qui part à la direction est recalculé à la main']],
    'FOR-0013': [['3 familles', 'L\'assistant répond · l\'agent exécute · le système coordonne'],
                 ['4 niveaux d\'autonomie', 'Propose · exécute sous accord · exécute et rend compte · décide seul'],
                 ['Point d\'arrêt', 'Juste avant la première action irréversible'], ['Traçabilité', 'Qui a décidé, quand, sur quelle donnée'],
                 ['Arrêt d\'urgence', 'Écrit, puis testé par quelqu\'un qui n\'a pas construit l\'agent']],
    'FOR-0014': [['Les 3 tâches', 'Chiffrées en heures par mois, classées par gain'], ['Qualifier', 'Interdit · haut risque · transparence · sans obligation particulière'],
                 ['Le coût de l\'erreur', 'En euros ET en réputation : il fixe l\'autonomie'], ['Le plan', 'Un seul agent en production les trois premiers mois'],
                 ['La grille YEBA', 'Coût complet · souveraineté · dépendance · compétence · réversibilité']],
    'FOR-0015': [['Où part la donnée ?', 'Appel distant · hébergement européen · exécution locale'], ['La preuve', 'Réseau coupé, sur toute la chaîne, interface comprise'],
                 ['Le bon modèle', 'Vitesse ET qualité mesurées sur la machine cible'], ['Le fonds documentaire', 'Un périmètre maîtrisé : pas tout le serveur'],
                 ['« Local »', 'Ne veut pas dire « hors RGPD » : registre et sécurité s\'appliquent']],
    'FOR-0017': [['C.A.D.R.E.', 'Contexte · Attentes · Données autorisées · Règles de confirmation · Exclusions'],
                 ['Connecter', 'Le minimum d\'autorisations, révocables en un geste'], ['Jamais d\'envoi seul', 'L\'assistant prépare, l\'humain valide et signe'],
                 ['Routines', 'Brief du matin · échéancier · relances, avec compte rendu'], ['Sécurité', 'Double authentification · méfiance envers les consignes cachées dans un courriel']],
}
