"""Les 10 questions du quiz — source unique pour la feuille papier, le corrigé et le jeu interactif.

Chaque question couvre un objectif contractuel ; la question 5 répond à un constat du positionnement
(2 répondantes sur 5 recommandaient 2 produits en fin de soin).
"""
QUIZ = [
    {"theme": "Accueil — première impression", "objectif": 2,
     "q": "La première impression d'une cliente qui entre à l'institut se fait :",
     "choix": ["À la fin du soin, en voyant le résultat", "Dans les toutes premières secondes, avant même un mot", "Au moment de payer"],
     "bonne": 1,
     "explication": "L'avis se forme en quelques secondes et se corrige difficilement ensuite. C'est ce que vous avez vécu à 8h00 avec « l'incident »."},
    {"theme": "Méthode S.O.I.N.", "objectif": 3,
     "q": "Dans S.O.I.N., la lettre N veut dire :",
     "choix": ["Négocier le prix", "Noter tout sur la fiche", "Nommer le besoin avec les mots de la cliente"],
     "bonne": 2,
     "explication": "Situer, Observer, Interroger, Nommer. Reformuler avec SES mots lui donne le sentiment d'être comprise."},
    {"theme": "Règle du pic et de la fin", "objectif": 2,
     "q": "D'un rendez-vous, une cliente retient surtout :",
     "choix": ["Le moment le plus fort et le tout dernier moment", "La moyenne de tous les moments", "Uniquement le prix"],
     "bonne": 0,
     "explication": "Règle du pic-fin (Kahneman, 1993) : la sortie de cabine et l'encaissement comptent plus qu'on ne le croit."},
    {"theme": "Bénéfice ou caractéristique", "objectif": 4,
     "q": "Laquelle de ces phrases est un BÉNÉFICE ?",
     "choix": ["« Ce sérum contient 12 % de vitamine C »", "« Vous retrouverez le teint lumineux dont vous me parliez »",
               "« C'est notre meilleure vente du mois »"],
     "bonne": 1,
     "explication": "Une caractéristique décrit le produit ; la preuve sociale décrit les autres clientes ; un bénéfice décrit SA vie à elle."},
    {"theme": "Méthode P.E.R.L.E.", "objectif": 4,
     "q": "En fin de soin, combien de produits recommandez-vous ?",
     "choix": ["Un seul, le plus utile pour son besoin", "Deux ou trois, pour lui laisser le choix", "Toute la gamme"],
     "bonne": 0,
     "explication": "R de P.E.R.L.E. : Recommander UNE chose. Deux produits, ce sont deux doutes. Si elle en veut plus, elle le demande."},
    {"theme": "Objection prix", "objectif": 5,
     "q": "La cliente dit : « C'est cher. » Votre première réaction :",
     "choix": ["Proposer une remise tout de suite", "Expliquer les charges de l'institut", "Accueillir, puis demander : « par rapport à quoi ? »"],
     "bonne": 2,
     "explication": "Questionner d'abord : est-ce le prix, le budget ou l'utilité ? Trois réponses différentes. Brader dévalorise ; se justifier déplace le débat."},
    {"theme": "Reprise de rendez-vous", "objectif": 6,
     "q": "Le prochain rendez-vous se propose idéalement :",
     "choix": ["Par SMS trois semaines plus tard", "À la sortie de cabine ou à l'encaissement, à chaque fois", "Seulement si la cliente le demande"],
     "bonne": 1,
     "explication": "Le taux de reprise en sortie de cabine est l'indicateur n°1 du remplissage de l'agenda."},
    {"theme": "Méthode A.R.P.", "objectif": 8,
     "q": "Votre responsable vous fait une remarque. La meilleure réponse :",
     "choix": ["« Oui mais ce n'est pas ma faute, parce que… »", "« D'accord. Si je comprends bien… Je propose de… »", "Ne rien dire"],
     "bonne": 1,
     "explication": "Accuser réception, Reformuler, Proposer. Ni justification, ni silence : on avance."},
    {"theme": "RGPD — fiche cliente", "objectif": 10,
     "q": "Une allergie notée sur une fiche cliente est :",
     "choix": ["Une donnée ordinaire", "Une donnée de santé, protégée : utile au soin seulement, jamais lue devant une autre cliente",
               "Une info à envoyer à l'autre institut par message perso"],
     "bonne": 1,
     "explication": "RGPD, article 9 : donnée de santé. Collecte limitée au nécessaire, accès restreint, discrétion, pas de messagerie personnelle."},
    {"theme": "IA — transparence", "objectif": 10,
     "q": "L'institut publie une photo « avant / après » retouchée par une intelligence artificielle. Il doit :",
     "choix": ["Ne rien dire", "Indiquer clairement que l'image a été générée ou modifiée par IA", "Ne jamais rien publier"],
     "bonne": 1,
     "explication": "Règlement européen sur l'IA (2024/1689), article 50 : une image retouchée par IA qui montre une vraie personne doit être signalée. "
                    "Et il faut l'accord écrit de la cliente pour publier sa photo (RGPD)."},
]
LETTRES = "ABC"
